'use strict';
const {JSDOM}=require('jsdom'),fs=require('fs'),assert=require('node:assert/strict');
(async()=>{
 const dom=new JSDOM('<body><p id="my-rentals-status"></p><div id="my-rentals-list"></div><button id="refresh-rentals"></button><button id="forget-rentals"></button><strong id="customer-total"></strong><strong id="customer-active"></strong><strong id="customer-returned"></strong></body>',{url:'https://example.test',runScripts:'outside-only',pretendToBeVisual:true});
 const w=dom.window;w.setTimeout=()=>1;w.clearTimeout=()=>{};w.confirm=()=>true;const token='a'.repeat(32);w.localStorage.setItem('tbp_rental_tokens',JSON.stringify([token]));let sends=0,supportStatus=null,fail=false;
 const row=()=>({token,reference:'TBP-TEST',station:'Station <img src=x>',battery:'B1',status:'active',rental_fee:100,deposit:0,duration_minutes:60,started_at:'2026-10-04 07:00:00',due_at:'2026-10-04 08:00:00',returned_at:null,support_status:supportStatus});
 w.fetch=async(url,options)=>{const body=JSON.parse(options.body);assert.equal(options.method,'POST');assert.equal(url.includes(token),false);if(url==='/my-rentals/support'){sends++;assert.equal(body.issue,'return');assert.equal(body.message,'Batterie rendue, retour non reconnu.');return {ok:!fail,json:async()=>fail?{error:'Service indisponible'}:{message:'Demande enregistrée'}};}return {ok:true,json:async()=>({rentals:[row()]})};};
 w.eval(fs.readFileSync('public/my-rentals.js','utf8'));await new Promise(setImmediate);const d=w.document;
 assert.equal(d.getElementById('customer-active').textContent,'1');assert.equal(d.querySelector('.customer-rental-card img'),null);assert.equal(d.querySelectorAll('input[type=radio]').length,4);
 const details=d.querySelector('details'),textarea=d.querySelector('textarea');details.open=true;d.querySelector('input[value=return]').checked=true;textarea.value='Batterie rendue, retour non reconnu.';textarea.dispatchEvent(new w.Event('input'));textarea.focus();
 d.getElementById('refresh-rentals').click();await new Promise(setImmediate);assert.equal(d.querySelector('textarea'),textarea);assert.equal(d.activeElement,textarea);assert.equal(details.open,true);assert.equal(textarea.value,'Batterie rendue, retour non reconnu.');assert.equal(d.querySelector('input[value=return]').checked,true);assert.equal(d.querySelector('.incident-counter').textContent,textarea.value.length+' / 2 000');
 const form=d.querySelector('form');fail=true;form.dispatchEvent(new w.Event('submit',{cancelable:true}));await new Promise(setImmediate);assert.match(d.querySelector('.incident-feedback').textContent,/indisponible/);assert.equal(d.querySelector('button[type=submit]').disabled,false);assert.equal(textarea.value,'Batterie rendue, retour non reconnu.');
 fail=false;form.dispatchEvent(new w.Event('submit',{cancelable:true}));form.dispatchEvent(new w.Event('submit',{cancelable:true}));await new Promise(setImmediate);assert.equal(sends,2,'Double submission blocked');assert.equal(d.querySelector('button[type=submit]').disabled,true);assert.equal(textarea.disabled,true);
 d.getElementById('refresh-rentals').click();await new Promise(setImmediate);assert.equal(details.dataset.sent,'1');assert.match(d.querySelector('.incident-feedback').textContent,/enregistrée/);
 d.getElementById('forget-rentals').click();assert.equal(d.querySelector('textarea'),null);assert.ok(d.querySelector('.customer-empty'));assert.equal(w.localStorage.getItem('tbp_rental_tokens'),null);dom.window.close();console.log('My rentals: statuses, escaped cards, radio incidents, counter, draft/focus preservation, retry, duplicate prevention, retained success and device erasure OK');
})().catch(e=>{console.error(e);process.exit(1)});
