<?php
declare(strict_types=1);
spl_autoload_register(static function(string $class):void {
 if(!str_starts_with($class,'App\\'))return;
 require dirname(__DIR__).'/app/'.str_replace('\\','/',substr($class,4)).'.php';
});
use App\Models\Rental;
use App\Services\PaiementProPayoutService;
use App\Services\PayoutCallbackAssessment;
use App\Services\PayoutResult;
use App\Services\PaymentVerification;
use App\Services\StationFleetService;

$tests=[];
$test=function(string $name,callable $fn)use(&$tests):void{$fn();$tests[]=$name;};
$same=static function(mixed $expected,mixed $actual,string $message=''):void{if($expected!==$actual)throw new RuntimeException(($message?$message.': ':'').'expected '.var_export($expected,true).', got '.var_export($actual,true));};

$test('initiation with session stays processing',fn()=>$same('processing',PayoutResult::initiation((object)['status'=>'INITIATED','code'=>0,'sessionid'=>'S1'])['state']));
$test('initiation without session is initiated, not paid',fn()=>$same('initiated',PayoutResult::initiation((object)['status'=>'INITIATED','code'=>0])['state']));
$test('ambiguous response is unknown',fn()=>$same('unknown',PayoutResult::initiation((object)['status'=>'OK'])['state']));
$test('explicit rejection is failed',fn()=>$same('failed',PayoutResult::initiation((object)['status'=>'FAILED','code'=>13])['state']));
$test('only pending settlements may be dispatched',function()use($same){$same(true,PayoutResult::dispatchable('pending'));$same(false,PayoutResult::dispatchable('initiated'));$same(false,PayoutResult::dispatchable('unknown'));$same(false,PayoutResult::dispatchable('failed'));});
$expected=['sessionid'=>'S1','referenceNo'=>'TBP-REFUND-2','amount'=>200,'currency'=>'XOF','channel'=>'WAVECI','payeeNo'=>'+2250748367710'];
$success=(object)($expected+['status'=>'SUCCESS']);
$test('fully matched status succeeds',fn()=>$same('succeeded',PayoutResult::finalStatus($success,$expected)));
$test('wrong beneficiary never succeeds',function()use($same,$success,$expected){$bad=clone $success;$bad->payeeNo='+2250102030405';$same('mismatch',PayoutResult::finalStatus($bad,$expected));});
$test('pending provider status remains processing',function()use($same,$expected){$same('processing',PayoutResult::finalStatus((object)['status'=>'INITIATED'],$expected));});
$test('ivorian local phone is normalized',fn()=>$same('+2250748367710',PaiementProPayoutService::normalizePhone('07 48 36 77 10')));
$test('return on time refunds all deposit',fn()=>$same(0,Rental::due(200,10,0)));
$test('one started late hour deducts ten percent',fn()=>$same(20,Rental::due(200,10,1)));
$test('late deduction is capped at deposit',fn()=>$same(200,Rental::due(200,10,3600*20)));
$payload=['referenceNo'=>'TBP-REFUND-2','amount'=>'200','merchantId'=>'PP-X','channel'=>'WAVECI','payeeNo'=>'0748367710','status'=>'SUCCESS'];
$callbackExpected=['reference'=>'TBP-REFUND-2','amount'=>200,'merchantId'=>'PP-X','channel'=>'WAVECI','payeeNo'=>'+2250748367710'];
$test('matching callback is still unauthenticated',fn()=>$same('false',PayoutCallbackAssessment::assess($payload,$callbackExpected)['authenticated']));
$test('repeated callbacks are deterministic and cannot transition state',fn()=>$same(PayoutCallbackAssessment::assess($payload,$callbackExpected),PayoutCallbackAssessment::assess($payload,$callbackExpected)));
$test('database enforces one settlement per rental',function()use($same){$schema=file_get_contents(dirname(__DIR__).'/database/schema.sql');$same(true,str_contains($schema,'rental_id BIGINT UNSIGNED NOT NULL UNIQUE'));});
putenv('PAYMENT_CALLBACK_SECRET='.str_repeat('a',64));
putenv('PAIEMENTPRO_MERCHANT_ID=PP-TEST');
$verification=new PaymentVerification;
$rental=['reference'=>'TBP-0123456789ABCDEF','payment_environment'=>'production','rental_fee'=>100,'deposit'=>0];
$notification=['merchantId'=>'PP-TEST','referenceNumber'=>$rental['reference'],'countryCurrencyCode'=>'952','amount'=>'100','responsecode'=>'0'];
$token=$verification->token($rental['reference']);
$test('valid payment notification is accepted',fn()=>$same(true,$verification->verified($notification,$rental,$token)));
$test('provider failure is classified without authorizing release',fn()=>$same('failed',$verification->outcome(array_replace($notification,['responsecode'=>'-1']),$rental,$token)));
$test('wrong amount has no authenticated outcome',fn()=>$same('invalid',$verification->outcome(array_replace($notification,['amount'=>'999']),$rental,$token)));
$test('callback without token is rejected',fn()=>$same(false,$verification->verified($notification,$rental,null)));
$test('wrong amount is rejected',fn()=>$same(false,$verification->verified(array_replace($notification,['amount'=>'999']),$rental,$token)));
$test('failure is rejected',fn()=>$same(false,$verification->verified(array_replace($notification,['responsecode'=>'-1']),$rental,$token)));
$test('wrong callback token is rejected',fn()=>$same(false,$verification->verified($notification,$rental,str_repeat('b',64))));
$test('payment and hardware callbacks have separate routes',function()use($same){
 $routes=file_get_contents(dirname(__DIR__).'/app/Core/App.php');
 $payment=file_get_contents(dirname(__DIR__).'/app/Services/PaiementProService.php');
 $same(true,str_contains($routes,"'POST /api/paiementpro/rental-callback' => [PaymentController::class, 'callback']"));
 $same(true,str_contains($payment,'/api/paiementpro/rental-callback?token='));
 $same(false,str_contains($payment,'/api/heycharge/callback?token='));
});
putenv('PAYMENT_CALLBACK_SECRET');putenv('PAIEMENTPRO_MERCHANT_ID');
$bank=['battery_id'=>'B1','slot_id'=>'2','lock_status'=>'1','battery_capacity'=>'45','battery_abnormal'=>'0','cable_abnormal'=>'0'];
$test('healthy charged power bank is rentable',fn()=>$same(true,StationFleetService::availableAt(['batteries'=>[$bank]],'B1','2')));
$test('wrong slot is not rentable',fn()=>$same(false,StationFleetService::availableAt(['batteries'=>[$bank]],'B1','3')));
$test('faulty power bank is not rentable',fn()=>$same(false,StationFleetService::rentable(array_replace($bank,['battery_abnormal'=>'1']))));
$test('empty power bank is not rentable',fn()=>$same(false,StationFleetService::rentable(array_replace($bank,['battery_capacity'=>'5']))));
fwrite(STDOUT,count($tests)." tests OK\n");
