'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),{JSDOM}=require('jsdom');
const pause=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{
 const dom=new JSDOM('<form id="station-profile" data-editable="1"><input id="station-latitude" value="5"><input id="station-longitude" value="-4"><input id="station-address"><input id="place-query"><div id="place-results"></div></form><p id="place-status"></p><div id="station-editor-map"></div><button id="clear-location"></button><button id="use-location"></button>',{runScripts:'outside-only',url:'https://example.test'});
 const w=dom.window;let requests=[],handlers={},markers=[];const map={setView(){return this},on(type,fn){handlers[type]=fn},removeLayer(){}};
 w.L={map:()=>map,tileLayer:()=>({addTo(){}}),divIcon:x=>x,latLng:(lat,lng)=>({lat,lng}),marker:(point,opts)=>{let pos=Array.isArray(point)?{lat:point[0],lng:point[1]}:point;const marker={setLatLng(p){pos=p;return this},getLatLng(){return pos},on(){return this},addTo(){return this},opts};markers.push(marker);return marker;}};
 w.fetch=async url=>{requests.push(url);return {ok:true,json:async()=>({results:[{label:'<script>bad</script> Café',latitude:5.35,longitude:-4.01}]})}};
 w.eval(fs.readFileSync('public/station-profile.js','utf8'));const query=w.document.getElementById('place-query');query.value='Café';query.dispatchEvent(new w.Event('input'));await pause(850);
 assert.equal(requests.length,1);assert.equal(w.document.getElementById('station-latitude').value,'5.0000000','Search preview never silently moves persisted position');assert.equal(w.document.querySelector('#place-results script'),null,'Suggestion text is escaped');w.document.querySelector('#place-results button').click();assert.equal(w.document.getElementById('station-latitude').value,'5.3500000');handlers.click({latlng:{lat:5.4,lng:-4.1}});assert.equal(w.document.getElementById('station-longitude').value,'-4.1000000');w.document.getElementById('clear-location').click();assert.equal(w.document.getElementById('station-latitude').value,'');dom.window.close();
 const readonly=new JSDOM('<form id="station-profile" data-editable="0"><input id="station-latitude" value="5"><input id="station-longitude" value="-4"><input id="station-address"></form><p id="place-status"></p><div id="station-editor-map"></div>',{runScripts:'outside-only'});readonly.window.L=w.L;handlers={};readonly.window.eval(fs.readFileSync('public/station-profile.js','utf8'));assert.equal(handlers.click,undefined,'Read-only map does not bind mutations');assert.equal(markers.at(-1).opts.draggable,false);readonly.window.close();
 const customer=new JSDOM('<p id="my-rentals-status"></p><div id="my-rentals-list"></div><button id="refresh-rentals"></button><button id="forget-rentals"></button>',{url:'https://example.test',runScripts:'outside-only',pretendToBeVisual:true});let request;customer.window.localStorage.setItem('tbp_rental_tokens',JSON.stringify(['a'.repeat(32)]));customer.window.fetch=async(url,options)=>{request={url,options};return {ok:true,json:async()=>({rentals:[{reference:'TBP-TEST',station:'<img src=x>',battery:'B1',status:'returned',rental_fee:100,deposit:0,duration_minutes:60,token:'a'.repeat(32),returned_at:'2026-10-04 01:00:00'}]})}};customer.window.eval(fs.readFileSync('public/my-rentals.js','utf8'));await pause(20);assert.equal(request.options.method,'POST');assert.equal(request.url.includes('aaaa'),false,'Bearer token never in URL');assert.equal(customer.window.document.querySelector('#my-rentals-list img'),null);assert.ok(customer.window.document.querySelector('a[href^="/rentals/receipt"]'));customer.window.close();
 console.log('Station/client DOM: debounced search, safe preview, selection, marker movement, removal, read-only behavior, private token requests and receipt OK');
})().catch(e=>{console.error(e);process.exit(1)});
