<?php
use App\Services\Auth;use App\Services\DepositWallet;use App\Services\XPayeWalletClient;
$esc=static fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');
$rules=json_decode($settings['fee_rules'],true)??[];$canWrite=Auth::can('finance.withdraw');
$labels=['pending'=>'Prêt à transférer','needs_fees'=>'Frais à renseigner','submitted'=>'Demande reçue — crédit à vérifier','unknown'=>'Résultat incertain — ne pas réémettre','confirmed'=>'Crédit payout rapproché'];
?>
<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Cautions et solde payout · Thiebapower</title><link rel="stylesheet" href="/style.css"><link rel="stylesheet" href="/statistics.css"><link rel="stylesheet" href="/deposit-wallet.css?v=20261003-1"><script src="/deposit-wallet.js?v=20261003-1" defer></script></head><body class="admin-body">
<?php $adminPageTitle='Cautions et solde payout';$adminPageSubtitle='Votre énergie, partout.';require __DIR__.'/partials/admin_shell_start.php';$csrf=$esc($_SESSION['csrf']); ?>
<main class="management-main wallet-page">
<section class="tb-hero tb-hero-compact"><span class="tb-eyebrow">ENCAISSEMENT → PAYOUT → CLIENT</span><h2>Chaque caution suit sa location.</h2><p>Le client paie le tarif de base et la caution. La caution et une réserve couvrant les frais de son remboursement sont transférées vers le solde payout. Le transfert interne entre les deux soldes est gratuit ; seuls les envois au client sont facturés, à 2 % par défaut. Après le retour physique confirmé, le client reçoit la caution restante par le même moyen que son paiement. Thieba Power paie les frais.</p><p>Un accusé de réception de la demande XPaye ne prouve pas le crédit du solde. Rapprochez le montant exact dans le compte fournisseur avant le reversement.</p></section>
<?php if($flash): ?><p role="status" class="management-card"><?= $esc($flash['message']) ?></p><?php endif; ?>
<div class="stats-cards"><?php foreach($totals as $total): ?><article class="management-card"><small><?= $esc($labels[$total['status']]??$total['status']) ?></small><h2><?= number_format((int)$total['amount'],0,',',' ') ?> FCFA</h2><p><?= (int)$total['count'] ?> transfert(s), essais inclus</p></article><?php endforeach; ?></div>
<section class="management-card"><h2>Activation et frais pris en charge</h2><p>Transferts automatiques : <strong><?= (int)$settings['enabled']===1?'activés':'désactivés' ?></strong> · Identifiants XPaye : <?= XPayeWalletClient::configured()?'renseignés':'à configurer sur le serveur' ?> · Remboursements automatiques : <?= \App\Core\App::env('AUTOMATIC_REFUNDS_ENABLED')==='1'?'activés':'désactivés sur le serveur' ?>.</p><p>La caution s’active dans <a href="/admin/pricing">Tarification</a>. Les frais ci-dessous doivent correspondre au contrat de payout. Exemple à 2 % sans frais fixes : caution 5 000 FCFA + 100 FCFA de frais réservés → transfert interne de 5 100 FCFA (1,02 × la caution). Si la retenue est de 200 FCFA, le client reçoit 4 800 FCFA ; les frais de cet envoi sont de 96 FCFA, payés depuis le solde payout.</p>
<?php if($canWrite && Auth::can('pricing.manage')): ?><form action="/admin/deposit-wallet" method="post"><input type="hidden" name="csrf" value="<?= $csrf ?>"><input type="hidden" name="action" value="settings"><div class="table-scroll"><table><thead><tr><th>Mode de réception</th><th>Barème confirmé</th><th>Frais fixes FCFA</th><th>Frais d’envoi (%)</th></tr></thead><tbody><?php foreach(['WAVECI'=>'Wave','MOMOCI'=>'MTN MoMo','OMCIV'=>'Orange Money','FLOOZ'=>'Moov Money'] as $key=>$label): ?><tr><td><?= $esc($label) ?></td><td><label><input type="checkbox" name="configured[<?= $key ?>]" value="1" <?= isset($rules[$key])?'checked':'' ?>> Confirmé</label></td><td><input aria-label="Frais fixes <?= $esc($label) ?>" type="number" name="fixed[<?= $key ?>]" min="0" max="100000" value="<?= (int)($rules[$key]['fixed']??0) ?>" required></td><td><input aria-label="Taux <?= $esc($label) ?>" type="number" name="percent[<?= $key ?>]" min="0" max="100" step="0.01" value="<?= $esc(number_format((int)($rules[$key]['basis_points']??DepositWallet::DEFAULT_FEE_BASIS_POINTS)/100,2,'.','')) ?>" required></td></tr><?php endforeach; ?></tbody></table></div><label><input type="checkbox" name="enabled" value="1" <?= (int)$settings['enabled']===1?'checked':'' ?>> Activer les transferts des nouvelles cautions payées via le worker</label><p><button class="admin-button">Enregistrer les paramètres</button></p></form><?php endif; ?></section>
<?php if($canWrite): ?><section class="management-card"><h2>Tester la connexion et le transfert</h2><p>Le test utilise les vrais soldes du compte XPaye configuré. Le montant de 100 FCFA est une valeur d’essai, indépendante du montant des cautions. Aucun remboursement client n’est déclenché par ce test.</p><form action="/admin/deposit-wallet" method="post"><input type="hidden" name="csrf" value="<?= $csrf ?>"><input type="hidden" name="action" value="auth"><button class="admin-button">Vérifier la connexion sans transfert</button></form><form action="/admin/deposit-wallet" method="post"><input type="hidden" name="csrf" value="<?= $csrf ?>"><input type="hidden" name="action" value="test"><input type="hidden" name="request_key" value="<?= bin2hex(random_bytes(16)) ?>"><p><label>Montant FCFA <input type="number" name="amount" min="1" max="100000" value="100" required></label></p><label><input type="checkbox" name="confirm_real" value="1" required> Je demande ce transfert réel du solde encaissement vers le solde payout.</label><p><button class="admin-button">Envoyer le transfert d’essai</button></p></form><p>Pour tester le parcours complet, effectuez une location payée avec caution puis restituez la batterie dans un terminal : la ligne ci-dessous relie l’encaissement, le transfert, la retenue et le remboursement. Les simulations et paiements sandbox n’utilisent pas les soldes réels.</p></section><?php endif; ?>
<section class="management-card"><h2>Suivi des cautions et des transferts</h2><label><input type="checkbox" id="wallet-live"> Activer le suivi en temps réel (toutes les 5 secondes)</label><p id="wallet-live-status" role="status">Montants calculés à l’ouverture. Activez le suivi pour les actualiser.</p><p>Les 100 derniers transferts sont affichés. Les montants à restituer concernent uniquement les cautions payées et vérifiées. Les retenues sont figées au retour physique.</p><div class="table-scroll"><table><thead><tr><th>Location / batterie</th><th>Client / réception</th><th>Caution / retenue / reste</th><th>Transfert / frais réservés</th><th>Crédit payout</th><th>Remboursement client</th><th>Actions / preuve</th></tr></thead><tbody>
<?php foreach($rows as $row): $remaining=$row['rental_id']?DepositWallet::remaining($row):['paid'=>false]; ?><tr data-wallet-rental="<?= (int)$row['rental_id'] ?>"><td><?= $row['reference']?'<a href="/admin/rentals/detail?reference='.rawurlencode($row['reference']).'">'.$esc($row['reference']).'</a>':'Essai #'.(int)$row['id'] ?><br><?= $esc($row['serial']??'') ?><br><small><?= $esc($row['created_at']) ?> UTC</small></td><td><?= $esc($row['customer_name']??'') ?><br><?= $esc($row['customer_phone']??'') ?><br><?= $esc($row['payout_channel']??'') ?></td><td data-wallet-remaining><?php if($remaining['paid']): ?>Payée : <?= (int)$remaining['deposit'] ?> FCFA<br>Retenue : <?= (int)$remaining['deduction'] ?> FCFA<br><strong>À restituer : <?= (int)$remaining['refund'] ?> FCFA</strong><?php else: ?>—<?php endif; ?></td><td><?= (int)$row['amount'] ?> FCFA<br>Dont frais réservés : <?= (int)$row['fee_reserve'] ?> FCFA<br><small>Le reliquat reste dans le solde payout.</small></td><td><?= $esc($labels[$row['status']]??$row['status']) ?><br><?php if($row['http_status']): ?>HTTP <?= (int)$row['http_status'] ?><?php endif; ?><br><small><?= $esc($row['response_summary']??'') ?></small></td><td><?= $row['refund_status']?$esc(['pending'=>'En attente','processing'=>'En cours','refunded'=>'Restitution confirmée','initiated'=>'Autorisation à vérifier','unknown'=>'À vérifier','failed'=>'Échec'][$row['refund_status']]??$row['refund_status']):'Aucun retour à rembourser' ?><br><?= isset($row['refund_amount'])?(int)$row['refund_amount'].' FCFA':'' ?></td><td><?= $esc($row['confirmation_proof']??'') ?>
<?php if($canWrite && $row['status']==='pending'): ?><form method="post" action="/admin/deposit-wallet"><input type="hidden" name="csrf" value="<?= $csrf ?>"><input type="hidden" name="action" value="send"><input type="hidden" name="id" value="<?= (int)$row['id'] ?>"><button class="admin-button">Transférer</button></form><?php endif; ?>
<?php if($canWrite && in_array($row['status'],['submitted','unknown'],true)): ?><form method="post" action="/admin/deposit-wallet"><input type="hidden" name="csrf" value="<?= $csrf ?>"><input type="hidden" name="action" value="confirm"><input type="hidden" name="id" value="<?= (int)$row['id'] ?>"><input name="proof" placeholder="Référence du crédit XPaye" minlength="5" maxlength="240" required aria-label="Preuve du crédit"><label><input type="checkbox" name="credit_checked" value="1" required> Crédit exact de <?= (int)$row['amount'] ?> FCFA vérifié</label><button class="admin-button">Rapprocher le crédit</button></form><?php endif; ?></td></tr><?php endforeach; ?>
</tbody></table></div></section></main><?php require __DIR__.'/partials/admin_shell_end.php'; ?></body></html>
