<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Caisse et points financiers · Thiebapower</title><link rel="stylesheet" href="/style.css"></head><body class="admin-body">
<?php $adminPageTitle='Caisse et points financiers';$adminPageOverline='GESTION FINANCIÈRE';$adminPageSubtitle='Encaissements confirmés, cautions et caisse physique';require __DIR__.'/partials/admin_shell_start.php';
$money=static fn(int $n)=>number_format($n,0,',',' ').' FCFA';$escape=static fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8'); ?>
<main class="admin-main finance-page">
 <section class="admin-card"><div class="admin-section-heading"><div><span class="admin-overline">RETRAIT MOBILE MONEY</span><h2>Retirer via Paiement Pro</h2><p>Le retrait est envoyé au bénéficiaire indiqué. Il ne constitue pas une sortie de caisse physique. Le statut est confirmé auprès de Paiement Pro ; une réponse d’initiation ne prouve pas le versement.</p></div></div>
 <?php if(App\Services\Auth::can('finance.withdraw')): ?>
 <form method="post" action="/admin/finance/withdraw" class="finance-entry" id="withdrawal-form">
 <input type="hidden" name="csrf" value="<?= $escape($_SESSION['csrf']) ?>"><input type="hidden" name="request_token" value="<?= bin2hex(random_bytes(16)) ?>">
 <label>Bénéficiaire<input name="recipient_name" maxlength="120" required></label><label>Numéro récepteur<input name="phone" type="tel" placeholder="+225 07 00 00 00 00" required></label>
 <label>Montant FCFA<input name="amount" type="number" min="1" max="999999999" required></label><label>Mode de réception<select name="channel" required><option value="WAVECI">Wave</option><option value="OMCIV">Orange Money</option><option value="MOMOCI">MTN MoMo</option><option value="FLOOZ">Moov Money</option></select></label>
 <label>Motif<input name="reason" maxlength="250" required></label><label><input type="checkbox" name="confirm" value="1" required> Je confirme ce versement réel au numéro indiqué.</label><button class="admin-button">Vérifier et envoyer le retrait</button>
 </form><script>document.getElementById('withdrawal-form').addEventListener('submit',e=>{const f=e.currentTarget;const message=`Confirmer le retrait réel de ${f.elements.amount.value} FCFA vers ${f.elements.phone.value} (${f.elements.channel.selectedOptions[0].textContent}), au nom de ${f.elements.recipient_name.value} ?`;if(!window.confirm(message)){e.preventDefault();return;}f.querySelector('button').disabled=true;});</script>
 <?php endif; ?>
 <div class="admin-table-wrap"><table><thead><tr><th>Date UTC</th><th>Référence</th><th>Bénéficiaire / numéro</th><th>Mode</th><th>Montant</th><th>État</th><th>Motif / action</th></tr></thead><tbody><?php foreach($withdrawals as $op): ?><tr><td><?= $escape($op['created_at']) ?></td><td><?= $escape($op['reference']) ?></td><td><?= $escape($op['recipient_name']) ?><br><?= $escape($op['recipient_phone']) ?></td><td><?= $escape($op['recipient_channel']) ?></td><td><?= $money((int)$op['amount']) ?></td><td><?= $escape(['unknown'=>'À vérifier','initiated'=>'Initié','processing'=>'En traitement','succeeded'=>'Versé confirmé','failed'=>'Refusé'][$op['status']]??$op['status']) ?></td><td><?= $escape($op['reason']) ?><?php if(App\Services\Auth::can('finance.withdraw') && in_array($op['status'],['unknown','initiated','processing'],true)): ?><form action="/admin/finance/withdraw/verify" method="post"><input type="hidden" name="csrf" value="<?= $escape($_SESSION['csrf']) ?>"><input type="hidden" name="reference" value="<?= $escape($op['reference']) ?>"><button class="admin-button">Vérifier le versement</button></form><?php if(!empty($withdrawalUrls[$op['reference']])): ?><a class="tb-link-button" href="<?= $escape($withdrawalUrls[$op['reference']]) ?>" target="_blank" rel="noopener noreferrer">Autoriser chez Paiement Pro</a><?php endif; ?><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div></section>

 <section class="admin-card"><div class="admin-section-heading"><div><span class="admin-overline">PÉRIODE UTC</span><h2>Point financier</h2><p>Les paiements sont comptés à la première notification de succès vérifiée. Les essais sandbox, réservations et remboursements non confirmés sont exclus.</p></div></div>
 <form class="finance-filter" method="get"><label>Du <input type="date" name="from" value="<?= $escape($start) ?>" required></label><label>Au <input type="date" name="to" value="<?= $escape($end) ?>" required></label><button class="admin-button">Afficher le point</button></form></section>
 <section class="finance-summary" aria-label="Synthèse Paiement Pro"><article><span>Retraits confirmés</span><strong><?= $money($report['withdrawn']) ?></strong></article><article><span>Locations encaissées</span><strong><?= $money($report['rentalRevenue']) ?></strong><small><?= count($report['payments']) ?> paiements confirmés</small></article><article><span>Cautions encaissées</span><strong><?= $money($report['depositsCollected']) ?></strong></article><article><span>Cautions remboursées</span><strong><?= $money($report['refunded']) ?></strong><small>Reversements confirmés sur la période</small></article><article><span>Flux net Paiement Pro</span><strong><?= $money($report['providerNet']) ?></strong><small>Encaissements moins remboursements et retraits confirmés</small></article></section>
 <section class="admin-card"><div class="admin-section-heading"><div><span class="admin-overline">PAR JOUR</span><h2>Points financiers quotidiens</h2></div></div><div class="admin-table-wrap"><table><thead><tr><th>Date UTC</th><th>Paiements reçus</th><th>Cautions remboursées</th><th>Flux net Paiement Pro</th><th>Entrées de caisse</th><th>Sorties de caisse</th></tr></thead><tbody><?php foreach($report['daily'] as $row): ?><tr><td><?= $escape($row['date']) ?></td><td><?= $money($row['collected']) ?></td><td><?= $money($row['refunded']) ?></td><td><?= $money($row['collected']-$row['refunded']-$row['withdrawn']) ?></td><td><?= $money($row['cashIn']) ?></td><td><?= $money($row['cashOut']) ?></td></tr><?php endforeach; ?><?php if(!$report['daily']): ?><tr><td colspan="6">Aucune opération confirmée sur la période.</td></tr><?php endif; ?></tbody></table></div></section>
 <section class="admin-card"><div class="admin-section-heading"><div><span class="admin-overline">PRODUCTION UNIQUEMENT</span><h2>Encaissements Paiement Pro</h2></div></div><div class="admin-table-wrap"><table><thead><tr><th>Confirmé UTC</th><th>Référence</th><th>Location</th><th>Caution</th><th>Total</th></tr></thead><tbody><?php foreach($report['payments'] as $row): ?><tr><td><?= $escape($row['paid_at']) ?></td><td><?= $escape($row['reference']) ?></td><td><?= $money((int)$row['rental_fee']) ?></td><td><?= $money((int)$row['deposit']) ?></td><td><?= $money((int)$row['rental_fee']+(int)$row['deposit']) ?></td></tr><?php endforeach; ?><?php if(!$report['payments']): ?><tr><td colspan="5">Aucun encaissement confirmé sur la période.</td></tr><?php endif; ?></tbody></table></div></section>
 <section class="admin-card"><div class="admin-section-heading"><div><span class="admin-overline">CAUTIONS</span><h2>Reversements confirmés</h2></div></div><div class="admin-table-wrap"><table><thead><tr><th>Confirmé UTC</th><th>Location</th><th>Remboursé</th><th>Retenue</th></tr></thead><tbody><?php foreach($report['refunds'] as $row): ?><tr><td><?= $escape($row['confirmed_at']) ?></td><td><?= $escape($row['reference']) ?></td><td><?= $money((int)$row['refund_amount']) ?></td><td><?= $money((int)$row['deduction']) ?></td></tr><?php endforeach; ?><?php if(!$report['refunds']): ?><tr><td colspan="4">Aucun reversement confirmé et daté sur la période.</td></tr><?php endif; ?></tbody></table></div><p class="finance-hint">Les reversements historiques antérieurs à l'installation de ce module n'ont pas de date de confirmation fiable et ne figurent pas dans le total de la période.</p></section>
 <section class="admin-card"><div class="admin-section-heading"><div><span class="admin-overline">ESPÈCES / CAISSE MANUELLE</span><h2>Journal de caisse</h2><p>Les écritures de caisse ne sont jamais fusionnées avec les transactions Paiement Pro.</p></div></div><div class="finance-summary finance-summary-cash"><article><span>Solde d'ouverture</span><strong><?= $money($report['openingCash']) ?></strong></article><article><span>Entrées</span><strong><?= $money($report['cashIn']) ?></strong></article><article><span>Sorties</span><strong><?= $money($report['cashOut']) ?></strong></article><article><span>Solde de clôture</span><strong><?= $money($report['cashBalance']) ?></strong></article></div>
 <?php if(App\Services\Auth::can('finance.manage')): ?><form class="finance-entry" method="post" action="/admin/finance/cash"><input type="hidden" name="csrf" value="<?= $escape($_SESSION['csrf']) ?>"><label>Sens <select name="direction" required><option value="in">Entrée</option><option value="out">Sortie</option></select></label><label>Montant FCFA <input type="number" name="amount" min="1" max="999999999" required></label><label>Date <input type="date" name="occurred_at" max="<?= gmdate('Y-m-d') ?>" value="<?= gmdate('Y-m-d') ?>" required></label><label>Motif <input name="category" maxlength="80" required></label><label>Référence pièce <input name="reference" maxlength="100" pattern="[A-Za-z0-9][A-Za-z0-9._-]{2,99}" required></label><label>Note <input name="note" maxlength="500"></label><button class="admin-button">Enregistrer l'écriture</button></form><?php endif; ?>
 <div class="admin-table-wrap"><table><thead><tr><th>Date UTC</th><th>Sens</th><th>Montant</th><th>Motif</th><th>Pièce</th><th>Note</th><th>Saisi par</th></tr></thead><tbody><?php foreach($report['cash'] as $row): ?><tr><td><?= $escape($row['occurred_at']) ?></td><td><?= $row['direction']==='in'?'Entrée':'Sortie' ?></td><td><?= $money((int)$row['amount']) ?></td><td><?= $escape($row['category']) ?></td><td><?= $escape($row['reference']) ?></td><td><?= $escape($row['note']) ?></td><td><?= $escape($row['actor']??'Compte supprimé') ?></td></tr><?php endforeach; ?><?php if(!$report['cash']): ?><tr><td colspan="7">Aucune écriture de caisse sur cette période.</td></tr><?php endif; ?></tbody></table></div></section>
</main><?php require __DIR__.'/partials/admin_shell_end.php'; ?></body></html>
