<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Scanner pour louer · Thiebapower</title><link rel="stylesheet" href="/style.css"><link rel="stylesheet" href="/public-entry.css?v=20261004-2"></head>
<body class="kiosk kiosk-qr-page public-entry public-home"><?php require __DIR__.'/partials/public_header.php'; ?>
<main class="kiosk-qr-shell"><section class="kiosk-qr-copy"><span class="kiosk-tag">LIBRE SERVICE · CÔTE D’IVOIRE</span><h1>Gardez le rythme.<br><em>Restez chargé.</em></h1><p>Scannez le QR code avec votre téléphone. Choisissez une batterie, réglez votre location et récupérez-la dans la station.</p><ol class="public-cycle" aria-label="Les quatre étapes de votre location"><li class="public-cycle-step cycle-step-1"><span class="cycle-icon"><svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><rect x="6" y="4" width="12" height="17" rx="3"/><path d="M10 4V2h4v2m-1 5-3 4h4l-3 4"/></svg><span class="cycle-number" aria-hidden="true">1</span></span><span class="cycle-copy"><strong>Choisissez</strong><small>votre batterie</small></span><svg class="cycle-arrow" viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="M4 12h15m-6-6 6 6-6 6"/></svg></li><li class="public-cycle-step cycle-step-2"><span class="cycle-icon"><svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><rect x="5" y="2" width="14" height="20" rx="3"/><path d="m9 11 2 2 4-4M10 18h4"/></svg><span class="cycle-number" aria-hidden="true">2</span></span><span class="cycle-copy"><strong>Payez</strong><small>depuis votre téléphone</small></span><svg class="cycle-arrow" viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="M4 12h15m-6-6 6 6-6 6"/></svg></li><li class="public-cycle-step cycle-step-3"><span class="cycle-icon"><svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="M4 3h16v11H4zM8 7h8M12 14v7m-4-4 4 4 4-4"/></svg><span class="cycle-number" aria-hidden="true">3</span></span><span class="cycle-copy"><strong>Récupérez</strong><small>la batterie dans la station</small></span><svg class="cycle-arrow" viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="M4 12h15m-6-6 6 6-6 6"/></svg></li><li class="public-cycle-step cycle-step-4"><span class="cycle-icon"><svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="M4 12v9h16v-9M8 17h8M12 3v10m-4-6 4-4 4 4"/></svg><span class="cycle-number" aria-hidden="true">4</span></span><span class="cycle-copy"><strong>Rapportez-la</strong><small>dans une station</small></span><svg class="cycle-arrow" viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="M4 12h15m-6-6 6 6-6 6"/></svg></li></ol><?php if(\App\Services\PromotionService::enabled()): ?><p><a href="/offers">Découvrir les codes promo →</a></p><?php endif; ?></section>
<section class="kiosk-qr-panel" aria-label="QR code de location">
<?php if($selected!==''&&$qr): ?>
 <span class="admin-overline">STATION THIEBAPOWER</span><h2>Scannez pour louer</h2><div class="kiosk-qr-art"><?= $qr ?></div><?php require __DIR__.'/partials/payment_logos.php'; ?><?php $stationName=$selected; foreach($stations as $item){if($item['imei']===$selected){$stationName=$item['label']?:$selected;break;}} ?><p class="station-identity"><?= htmlspecialchars($stationName,ENT_QUOTES,'UTF-8') ?></p><p>Ouvrez l’appareil photo de votre téléphone et pointez-le sur ce QR code.</p>
 <?php if(count($stations)>1): ?><nav class="kiosk-station-switch" aria-label="Choisir une station"><?php foreach($stations as $item): ?><a <?= $item['imei']===$selected?'aria-current="page"':'' ?> href="/?kiosk=<?= rawurlencode($item['imei']) ?>"><?= htmlspecialchars($item['label']?:$item['imei'],ENT_QUOTES,'UTF-8') ?></a><?php endforeach; ?></nav><?php endif; ?>
<?php else: ?><h2>Service indisponible</h2><p>Aucune station active avec une étiquette QR valide.</p><?php endif; ?>
</section></main><footer class="kiosk-footer"><span>THIEBAPOWER · Libre service en Côte d’Ivoire</span><span>Louez. Rechargez. Continuez.</span></footer></body></html>
