<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SMS Orange CI · Thiebapower</title><link rel="stylesheet" href="/style.css"><link rel="stylesheet" href="/orange-sms.css?v=1"></head><body class="admin-body">
<?php $adminPageTitle='SMS Orange CI'; require __DIR__.'/partials/admin_shell_start.php'; $h=static fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8'); $_SESSION['orange_sms_nonce']=bin2hex(random_bytes(24)); $csrf=static function() use($h){ ?><input type="hidden" name="csrf" value="<?= $h($_SESSION['csrf']) ?>"><?php }; ?>
<main class="management-main orange-sms">
<section class="management-card"><h2>Préparer vos communications SMS</h2><p>Configurez Orange, vérifiez votre crédit puis testez l’envoi. L’intégration reste indépendante des notifications de location : aucun SMS automatique n’est déclenché par ces réglages.</p><div class="sms-status"><span><?= $settings['enabled']?'Activée':'Désactivée' ?></span><span><?= $settings['mode']==='production'?'Production · SMS facturés':'Simulation · aucun SMS envoyé' ?></span><span><?= $secretConfigured?'Secret configuré':'Secret à renseigner' ?></span></div><p>L’adresse technique CI est <code>tel:+2250000</code>. Le nom affiché sur le téléphone est celui autorisé par Orange.</p></section>
<?php if(!$installed): ?><p role="alert">Appliquez d’abord la migration <code>20261004_orange_sms.sql</code> pour enregistrer les paramètres et les tests.</p><?php endif; ?>
<?php if($result): ?><section class="management-card" role="status">
<?php if(isset($result['error'])): ?><p role="alert"><?= $h($result['error']) ?></p><?php elseif(isset($result['notice'])): ?><p><?= $h($result['notice']) ?></p><?php else: ?>
<h2>Résultat du contrôle</h2><p><?= $h(['authenticated'=>'Authentification réussie.','simulated'=>'Simulation réussie. Aucun SMS envoyé et aucun crédit consommé.','accepted'=>'SMS accepté par Orange. La livraison au téléphone n’est pas encore confirmée.','rejected'=>'SMS refusé par Orange. Vérifiez le crédit, la souscription et l’expéditeur.','unknown'=>'Résultat inconnu. Vérifiez chez Orange avant de recommencer.','checked'=>'Consultation réussie.'][$result['state']]??$result['state']) ?></p>
<?php if($result['http_status']!==null): ?><p>HTTP <?= $h($result['http_status']) ?></p><?php endif; ?><?php if(isset($result['expires_in'])): ?><p>Validité du jeton : <?= $h($result['expires_in']) ?> secondes. Le jeton reste côté serveur.</p><?php endif; ?>
<?php if(isset($result['data'])): ?><details><summary>Données Orange · <?= $h(['balance'=>'solde et contrats','usage'=>'consommation','purchases'=>'achats'][$result['operation']]??'contrôle') ?></summary><pre><?= $h(json_encode($result['data'],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)) ?></pre></details><?php endif; ?>
<?php endif; ?></section><?php endif; ?>
<?php if(Auth::can('sms.manage')): ?><form method="post" action="/admin/sms/settings" class="management-card"><?php $csrf(); ?><h2>Paramètres de l’intégration</h2><div class="sms-grid">
<div>État<label class="sms-check"><input type="checkbox" name="enabled" <?= $settings['enabled']?'checked':'' ?>> Activer l’intégration SMS</label></div>
<label>Mode<select name="mode"><option value="simulation" <?= $settings['mode']==='simulation'?'selected':'' ?>>Simulation</option><option value="production" <?= $settings['mode']==='production'?'selected':'' ?>>Production</option></select></label>
<label>Client ID<input name="client_id" maxlength="190" value="<?= $h($settings['client_id']) ?>" autocomplete="off"><small>Identifiant de votre application Orange Developer. Peut aussi être fourni dans le fichier .env.</small></label>
<label>Client Secret<input type="password" name="client_secret" maxlength="4096" autocomplete="new-password" value=""><small>Laissez vide pour conserver le secret existant. Il n’est jamais affiché.</small></label>
<label>Adresse technique CI<input name="sender_address" value="<?= $h($settings['sender_address']) ?>" readonly></label>
<label>Nom expéditeur personnalisé<input name="sender_name" maxlength="11" value="<?= $h($settings['sender_name']) ?>" placeholder="THIEBAPOWER"><small>Obligatoire en production pour Orange CI. 11 caractères alphanumériques maximum.</small></label>
</div><label class="sms-check"><input type="checkbox" name="sender_approved" <?= $settings['sender_approved']?'checked':'' ?>> Orange a confirmé l’approbation de ce nom expéditeur.</label><p>Orange CI impose un nom expéditeur approuvé et autorisé. Saisissez exactement le nom confirmé par Orange. Un crédit SMS et une souscription Orange SMS CI sont nécessaires en production.</p><button class="admin-button" <?= !$installed?'disabled':'' ?>>Enregistrer les paramètres</button></form><?php endif; ?>
<?php if(Auth::can('sms.test')): ?><section class="management-card"><h2>Vérifier la connexion et le compte</h2><p>Ces contrôles interrogent réellement Orange, même en mode simulation ou lorsque l’envoi est désactivé. Ils n’envoient aucun SMS. Attendez 30 secondes entre deux opérations.</p><div class="sms-actions"><?php foreach(['auth'=>'Tester l’authentification','balance'=>'Consulter le solde','usage'=>'Voir la consommation','purchases'=>'Historique des achats'] as $op=>$label): ?><form method="post" action="/admin/sms/test"><?php $csrf(); ?><input type="hidden" name="operation" value="<?= $op ?>"><button class="admin-ghost" <?= !$installed?'disabled':'' ?>><?= $h($label) ?></button></form><?php endforeach; ?></div></section>
<form method="post" action="/admin/sms/test" class="management-card"><?php $csrf(); ?><input type="hidden" name="operation" value="send"><input type="hidden" name="nonce" value="<?= $h($_SESSION['orange_sms_nonce']) ?>"><h2>Envoyer un SMS de test</h2><div class="sms-grid"><label>Numéro destinataire<input name="recipient" type="tel" required placeholder="+2250700000000" maxlength="32"><small>Numéro ivoirien à 10 chiffres ou au format +225.</small></label><label>Message<textarea name="message" required maxlength="160" rows="3">Thiebapower : test de connexion SMS Orange CI.</textarea></label></div><p>Un message contenant des accents ou des caractères Unicode peut consommer plusieurs unités SMS. Le test est limité à 160 caractères.</p><?php if($settings['mode']==='production'): ?><label class="sms-check"><input type="checkbox" name="confirm_real" required> Je confirme l’envoi réel à ce numéro et la consommation du crédit Orange.</label><?php endif; ?><button class="admin-button" <?= !$installed||!$settings['enabled']?'disabled':'' ?>><?= $settings['mode']==='production'?'Envoyer le SMS réel':'Simuler l’envoi' ?></button></form><?php endif; ?>
<section class="management-card"><h2>Historique des 50 dernières opérations</h2><p>Les numéros sont masqués. Les messages, secrets et jetons ne sont pas enregistrés dans cet historique. « Accepté » signifie accepté par l’API ; le suivi de livraison nécessitera un accusé de réception Orange.</p><div class="sms-table"><table><thead><tr><th>Date UTC</th><th>Opération</th><th>Mode</th><th>Destinataire</th><th>État</th><th>HTTP</th><th>Référence Orange</th></tr></thead><tbody><?php foreach($history as $row): ?><tr><?php foreach(['created_at','operation','mode','recipient_masked','state','http_status','resource_id'] as $key): ?><td><?= $h($key==='state'?(['processing'=>'En cours / à vérifier','simulated'=>'Simulé','accepted'=>'Accepté','rejected'=>'Refusé','unknown'=>'Inconnu','authenticated'=>'Authentifié','checked'=>'Contrôlé','failed'=>'Échec'][$row[$key]]??$row[$key]):$row[$key]??'—') ?></td><?php endforeach; ?></tr><?php endforeach; ?><?php if(!$history): ?><tr><td colspan="7">Aucune opération.</td></tr><?php endif; ?></tbody></table></div></section>
</main><?php require __DIR__.'/partials/admin_shell_end.php'; ?></body></html>
