<!doctype html>
<html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Reversements Paiement Pro · Thiebapower</title>
<style>
:root{font-family:system-ui,-apple-system,Segoe UI,sans-serif;color:#172b3a;background:#f4f7fb}*{box-sizing:border-box}body{margin:0;background:#f4f7fb;color:#172b3a}a{color:#1261a0}main{max-width:1120px;margin:0 auto;padding:28px 20px 80px}.top{display:flex;justify-content:space-between;align-items:center;gap:20px;margin-bottom:26px}.brand{color:#1261a0;font-weight:850;letter-spacing:.08em}.brand span{color:#f29b38}h1{font-size:clamp(30px,4vw,44px);margin:8px 0}h2{font-size:21px;margin:0 0 12px}p{line-height:1.55;color:#43596a}.card{background:white;border:1px solid #dce6ed;box-shadow:0 5px 25px rgba(24,53,76,.05);border-radius:16px;padding:25px;margin:16px 0}.eyebrow{color:#387195;font-size:12px;font-weight:800;text-transform:uppercase;letter-spacing:.12em}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.notice{border-left:4px solid #de9220;background:#fff8eb;padding:12px 16px;border-radius:6px}.good{border-color:#228a68;background:#effaf5}.pill{display:inline-block;border-radius:50px;background:#e8f3fc;color:#205d86;padding:6px 10px;font-weight:700}.muted{color:#617585}.mono,code,pre{font-family:ui-monospace,SFMono-Regular,Consolas,monospace;overflow-wrap:anywhere}pre{white-space:pre-wrap;background:#f2f6f9;border:1px solid #dfe8ef;border-radius:10px;padding:15px;color:#1b3548;font-size:13px;line-height:1.5;margin:8px 0}label{display:block;font-weight:650;margin:14px 0;color:#243c4d}input,select{display:block;width:100%;border:1px solid #b7cad8;border-radius:9px;background:white;color:#172b3a;padding:12px;font:inherit;margin-top:6px}input:focus,select:focus{outline:3px solid #b9dffd;border-color:#2984c3}.check{display:flex;align-items:flex-start;gap:10px;line-height:1.45}.check input{width:20px;height:20px;flex:none;margin:1px 0}.button{border:0;border-radius:10px;background:#116b9a;color:white;padding:13px 18px;font:inherit;font-weight:750;cursor:pointer}.button:hover{background:#0c527a}.button:disabled{background:#9aabb7;cursor:not-allowed}.small{font-size:13px}.tablewrap{overflow-x:auto}table{width:100%;border-collapse:collapse;min-width:650px}th,td{text-align:left;padding:13px 10px;border-bottom:1px solid #e4ebf0;vertical-align:top;font-size:14px}th{color:#476277;background:#f5f8fb;font-size:12px;text-transform:uppercase}td .button{font-size:12px;padding:8px}.event{border:1px solid #e1eaf0;border-radius:12px;padding:14px;margin:10px 0}details summary{cursor:pointer;font-weight:700;color:#1c5c84}.footer{margin-top:30px;color:#617585}@media(max-width:760px){.grid{grid-template-columns:1fr}.top{align-items:flex-start;flex-direction:column}.card{padding:18px}}
</style></head><body><main>
<header class="top"><div><div class="brand">THIEBA<span>POWER</span></div><h1>Reversements Paiement Pro</h1><p>Tester uniquement l’API payout : paramètres envoyés, réponse SOAP et statut sur une seule page.</p></div><a href="/admin">← Tableau de bord</a></header>
<div class="grid"><section class="card"><div class="eyebrow">Connexion active</div><h2>Endpoint et méthode</h2><p>Environnement : <strong><?=htmlspecialchars($mode,ENT_QUOTES,'UTF-8')?></strong><br>WSDL : <span class="mono"><?=htmlspecialchars($endpoint?:'non configuré',ENT_QUOTES,'UTF-8')?></span><br>Méthode : <code>initTransact</code><br>Vérification : <code>getTransStatus(sessionid)</code></p><p class="small">Le token est calculé avec HMAC SHA-256 à partir du timestamp et de l’ID marchand. Sa valeur et la clé secrète restent masquées.</p></section>
<section class="card"><div class="eyebrow">État des essais payout</div><h2><?=$labOpen?> essai(s) en cours</h2><p>Chaque essai crée une nouvelle référence. Si un essai reste sans réponse certaine, cette référence n’est jamais relancée.</p><p class="notice good">Cette page ne lance aucun remboursement de caution.</p></section></div>
<section class="card"><div class="eyebrow">Dernière réponse reçue</div><h2><?php if($events):?><?=htmlspecialchars($events[0]['source'],ENT_QUOTES,'UTF-8')?> · <?=htmlspecialchars($events[0]['reference'],ENT_QUOTES,'UTF-8')?><?php else:?>Aucun appel de test enregistré<?php endif?></h2><?php if($events):?><pre><?=htmlspecialchars(json_encode(json_decode($events[0]['response'],true),JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE),ENT_QUOTES,'UTF-8')?></pre><p class="small muted"><?=htmlspecialchars($events[0]['created_at'],ENT_QUOTES,'UTF-8')?></p><?php else:?><p>Le statut, le code, la description et la session renvoyés par l’API apparaîtront ici après l’essai.</p><?php endif?></section>
<section class="card"><div class="eyebrow">Envoi contrôlé</div><h2>Tester un payout · 200 FCFA</h2><p>Une référence neuve sera créée. Le formulaire envoie un vrai paiement de 200 FCFA au numéro choisi.</p><?php if(!$enabled):?><p class="notice">Fonction désactivée : activer <code>PAYMENT_LAB_PAYOUT_ENABLED=1</code> dans <code>.env</code>.</p><?php elseif($labOpen):?><p class="notice">Un essai indépendant est déjà en cours ou inconnu. Vérifiez son issue avant un nouvel envoi.</p><?php endif?>
<div class="grid"><form method="post" action="/admin/payment-lab/payout"><input type="hidden" name="csrf" value="<?=htmlspecialchars($csrf,ENT_QUOTES,'UTF-8')?>"><label>Numéro du bénéficiaire<input name="phone" type="tel" required placeholder="+225..."></label><label>Canal<select name="channel" required><option value="">Sélectionner</option><option value="WAVECI">Wave CI</option><option value="MOMOCI">MTN MoMo CI</option><option value="OMCIV">Orange Money CI</option><option value="FLOOZ">Flooz</option></select></label><label class="check"><input type="checkbox" name="confirm_amount" value="200" required>Je confirme le versement réel de 200 FCFA.</label><button class="button" <?=$enabled&&$labOpen===0?'':'disabled'?>>Envoyer 200 FCFA à Paiement Pro</button></form>
<div><strong>Paramètres de l’appel</strong><pre>merchantId: ID configuré dans .env
currency: XOF
amount: 200
referenceNo: générée lors de l’envoi
channel: choix du formulaire
payeeNo: numéro du formulaire
clientName: Test Thiebapower
timestamp: horodatage de l’envoi
token: [HMAC masqué]
returnURL: https://thiebapower.com/payment/return
callbackURL: https://thiebapower.com/api/paiementpro/payout-callback</pre><p class="small muted">L’appel effectivement envoyé est archivé plus bas avec sa référence et ses paramètres filtrés.</p></div></div></section>

<section class="card"><div class="eyebrow">Historique des essais</div><h2>Réponses et sessions</h2><div class="tablewrap"><table><thead><tr><th>Référence</th><th>Montant</th><th>Session</th><th>Statut</th><th>Réponse</th><th>Suivi</th></tr></thead><tbody><?php foreach($operations as $op):?><tr><td class="mono"><?=htmlspecialchars($op['reference'],ENT_QUOTES,'UTF-8')?></td><td><?=(int)$op['amount']?> FCFA</td><td class="mono"><?=htmlspecialchars((string)($op['provider_session_id']??'—'),ENT_QUOTES,'UTF-8')?></td><td><span class="pill"><?=htmlspecialchars($op['status'],ENT_QUOTES,'UTF-8')?></span></td><td><?=htmlspecialchars((string)($op['provider_message']??'—'),ENT_QUOTES,'UTF-8')?></td><td><?php if($op['status']==='processing'&&$op['provider_session_id']):?><form method="post" action="/admin/payment-lab/reconcile"><input type="hidden" name="csrf" value="<?=htmlspecialchars($csrf,ENT_QUOTES,'UTF-8')?>"><input type="hidden" name="id" value="<?=(int)$op['id']?>"><button class="button">Vérifier</button></form><?php else:?>—<?php endif?></td></tr><?php endforeach?></tbody></table></div></section>
<div class="grid"><section class="card"><div class="eyebrow">Requêtes</div><h2>Paramètres réellement envoyés</h2><?php foreach($requests as $req):?><details class="event"><summary><?=htmlspecialchars($req['reference'],ENT_QUOTES,'UTF-8')?> · <?=htmlspecialchars($req['created_at'],ENT_QUOTES,'UTF-8')?></summary><p class="small mono"><?=htmlspecialchars($req['endpoint'],ENT_QUOTES,'UTF-8')?> · initTransact</p><pre><?=htmlspecialchars(json_encode(json_decode($req['parameters'],true),JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE),ENT_QUOTES,'UTF-8')?></pre></details><?php endforeach?><?php if(!$requests):?><p class="muted">Aucun appel archivé depuis l’installation de ce journal.</p><?php endif?></section>
<section class="card"><div class="eyebrow">Retours API</div><h2>Réponses et erreurs</h2><p class="small">Les callbacks sont non vérifiés et n’attestent pas le versement.</p><?php foreach($events as $event):?><details class="event"><summary><?=htmlspecialchars($event['reference'],ENT_QUOTES,'UTF-8')?> · <?=htmlspecialchars($event['source'],ENT_QUOTES,'UTF-8')?> · <?=htmlspecialchars($event['created_at'],ENT_QUOTES,'UTF-8')?></summary><pre><?=htmlspecialchars(json_encode(json_decode($event['response'],true),JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE),ENT_QUOTES,'UTF-8')?></pre></details><?php endforeach?><?php if(!$events):?><p class="muted">Aucune réponse archivée depuis l’installation de ce journal.</p><?php endif?></section></div>
<p class="footer">Le token HMAC et la clé secrète ne sont jamais affichés. Aucun bouton ne réémet une référence inconnue.</p></main></body></html>
