<!doctype html>
<html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#081b27"><title>THIEBAPOWER · Louer une batterie</title><link rel="stylesheet" href="/style.css"></head>
<body class="kiosk"><div class="kiosk-shell"><header class="kiosk-header"><a href="/" class="kiosk-logo">THIEBA<span>POWER</span></a><div class="kiosk-header-right"><span class="live-dot"></span> Énergie à portée de main</div></header>
<main class="kiosk-main"><aside class="kiosk-side"><span class="kiosk-tag">LIBRE-SERVICE · CÔTE D’IVOIRE</span><h1>Une batterie.<br><em>Votre liberté.</em></h1><p>Rechargez votre téléphone où que vous soyez. Suivez les étapes sur cet écran pour préparer votre location.</p><div class="bank-illustration" aria-hidden="true"><div class="bank-cap"></div><span>ϟ</span><small>THIEBAPOWER</small></div><div class="side-footer"><span>Tarif dès</span><strong><?=number_format((int)$prices['rental_fee'],0,',',' ')?> FCFA</strong><small>pour <?=(int)$prices['duration_minutes']?> minutes</small></div></aside>
<section class="kiosk-workflow" aria-label="Parcours de location"><div class="workflow-top"><span class="workflow-label">LOCATION DE POWERBANK</span><span class="workflow-step" id="step-counter">Étape 1 sur 3</span></div><div class="progress"><span id="progress-bar"></span></div>
<div class="kiosk-screen" data-step="1"><div class="screen-icon">▦</div><h2>Scannez la station</h2><p>Utilisez le QR code sur la station ou saisissez le code indiqué à côté.</p><button type="button" id="scan-button" class="touch-button outline">▣ &nbsp; Scanner le QR code</button><video id="scan-video" playsinline hidden></video><label class="input-label" for="station-code">Code de la station</label><input id="station-code" maxlength="120" autocomplete="off" placeholder="Saisir le code de la station"><p id="scan-result" class="screen-hint" role="status">La caméra ne s’active que lorsque vous appuyez sur Scanner.</p><button type="button" class="touch-button primary" id="station-next">Continuer <span aria-hidden="true">→</span></button></div>
<div class="kiosk-screen" data-step="2" hidden><button type="button" class="back-button" data-back="1">← Retour</button><div class="screen-icon">ϟ</div><h2>Choisissez une batterie</h2><p>Le montant de caution peut varier selon la batterie et peut être nul.</p><div class="battery-options" id="battery-options"><?php foreach($batteries as $b):?><button type="button" class="battery-option" data-serial="<?=htmlspecialchars($b['serial'],ENT_QUOTES,'UTF-8')?>" data-deposit="<?=(int)($b['deposit_override']??$prices['default_deposit'])?>"><span class="option-symbol">ϟ</span><span><strong><?=htmlspecialchars($b['serial'],ENT_QUOTES,'UTF-8')?></strong><small>Caution <?=number_format((int)($b['deposit_override']??$prices['default_deposit']),0,',',' ')?> FCFA</small></span><span class="option-arrow">→</span></button><?php endforeach?></div><?php if(!$batteries):?><div class="kiosk-notice">Aucune batterie disponible pour le moment.</div><?php endif?></div>
<div class="kiosk-screen" data-step="3" hidden><button type="button" class="back-button" data-back="2">← Retour</button><div class="screen-icon">✓</div><h2>Votre récapitulatif</h2><p>Vérifiez les montants avant tout paiement.</p><div class="receipt"><div><span>Station</span><strong id="summary-station">—</strong></div><div><span>Batterie</span><strong id="summary-battery">—</strong></div><div><span>Location · <?=(int)$prices['duration_minutes']?> min</span><strong id="summary-fee"><?=number_format((int)$prices['rental_fee'],0,',',' ')?> FCFA</strong></div><div><span>Caution restituable</span><strong id="summary-deposit">—</strong></div><div class="total"><span>Total à prévoir</span><strong id="summary-total">—</strong></div></div><p class="deposit-info">Retour dans le délai : caution restituée intégralement. Après le délai : <?=(int)$prices['late_percent']?> % de la caution retenus par heure supplémentaire entamée, dans la limite de la caution.</p><div class="kiosk-notice"><strong>Service en préparation</strong><br>La page de paiement et la libération des batteries ne sont pas encore activées. Aucun débit ne peut être effectué.</div><button class="touch-button primary" type="button" disabled>Procéder au paiement · prochainement</button></div>
</section></main><footer class="kiosk-footer"><span>THIEBAPOWER · Votre énergie, partout</span><span>Besoin d’aide ? Adressez-vous au personnel de la station.</span></footer></div><script>window.TB_PRICE=<?=(int)$prices['rental_fee']?>;</script><script src="/app.js" defer></script></body></html>
