<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Locations · Thiebapower</title><link rel="stylesheet" href="/style.css"></head>
<body class="management-page"><header class="management-header"><a class="kiosk-logo" href="/admin">THIEBA<span>POWER</span></a><nav><a href="/admin">Tableau de bord</a><a href="/admin/stations">Terminaux</a></nav></header>
<main class="management-main"><p class="admin-overline">EXPLOITATION</p><h1>Locations et incidents</h1>
<p>Vérifiez les paiements en attente auprès de Paiement Pro. Une sortie à issue inconnue se rapproche avec la station ; ne relancez jamais l’éjection à l’aveugle.</p>
<section class="management-card"><h2>Filtrer</h2><div class="management-grid"><a href="/admin/rentals">Toutes</a><?php foreach($counts as $count): ?><a href="/admin/rentals?status=<?= rawurlencode($count['status']) ?>"><?= htmlspecialchars($count['status'],ENT_QUOTES,'UTF-8') ?> (<?= (int)$count['quantity'] ?>)</a><?php endforeach; ?></div></section>
<section class="management-card"><h2><?= $status?htmlspecialchars($status,ENT_QUOTES,'UTF-8'):'Dernières locations' ?></h2><div class="management-table-wrap"><table><thead><tr><th>Référence</th><th>Station / batterie</th><th>Paiement</th><th>État</th><th>Création</th><th>Action</th></tr></thead><tbody>
<?php foreach($rentals as $r): ?><tr><td><strong><?= htmlspecialchars($r['reference'],ENT_QUOTES,'UTF-8') ?></strong><br><small><?= htmlspecialchars($r['customer_name'],ENT_QUOTES,'UTF-8') ?></small></td><td><a href="/admin/stations/detail?imei=<?= rawurlencode((string)$r['station_code']) ?>"><?= htmlspecialchars((string)$r['station_code'],ENT_QUOTES,'UTF-8') ?></a><br><?= htmlspecialchars($r['battery_serial'],ENT_QUOTES,'UTF-8') ?></td><td><?= number_format((int)$r['rental_fee']+(int)$r['deposit'],0,',',' ') ?> FCFA<br><small>Session <?= htmlspecialchars((string)($r['payment_session_id']??'—'),ENT_QUOTES,'UTF-8') ?></small></td><td><?= htmlspecialchars($r['status'],ENT_QUOTES,'UTF-8') ?><?php if($r['refund_status']): ?><br><small>Restitution <?= htmlspecialchars($r['refund_status'],ENT_QUOTES,'UTF-8') ?></small><?php endif; ?></td><td><?= htmlspecialchars($r['created_at'],ENT_QUOTES,'UTF-8') ?></td><td>
<?php if(in_array($r['status'],['releasing','release_failed','active'],true)): ?><form method="post" action="/admin/stations/reconcile"><input type="hidden" name="csrf" value="<?= htmlspecialchars($_SESSION['csrf'],ENT_QUOTES,'UTF-8') ?>"><input type="hidden" name="reference" value="<?= htmlspecialchars($r['reference'],ENT_QUOTES,'UTF-8') ?>"><button class="admin-ghost">Vérifier la station</button></form><?php endif; ?>
<?php if($r['status']==='pending_payment' && $r['reservation_expires_at'] && strtotime($r['reservation_expires_at'].' UTC')<=time()): ?><details><summary>Libérer après vérification</summary><form method="post" action="/admin/rentals/cancel" class="management-stack"><input type="hidden" name="csrf" value="<?= htmlspecialchars($_SESSION['csrf'],ENT_QUOTES,'UTF-8') ?>"><input type="hidden" name="reference" value="<?= htmlspecialchars($r['reference'],ENT_QUOTES,'UTF-8') ?>"><p>Vérifiez l’absence d’encaissement chez Paiement Pro. Un succès tardif sera classé à traiter, sans nouvelle éjection.</p><label>Recopier la référence<input name="confirm_reference" required></label><label>Preuve de contrôle fournisseur<input name="provider_proof" required minlength="6" maxlength="120"></label><button class="admin-ghost">Libérer la réservation</button></form></details><?php endif; ?>
<?php if($r['status']==='payment_review'): ?><strong>Paiement à rapprocher ou rembourser</strong><?php endif; ?>
</td></tr><?php endforeach; ?></tbody></table></div></section></main></body></html>
