<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Statistiques en direct · Thiebapower</title><link rel="stylesheet" href="/style.css"><link rel="stylesheet" href="/statistics.css?v=20261003-1"><script src="/statistics.js?v=20261003-1" defer></script></head><body class="admin-body">
<?php $adminPageTitle='Statistiques en direct';$adminPageSubtitle='Votre énergie, partout. Votre activité, sous contrôle.';require __DIR__.'/partials/admin_shell_start.php'; ?>
<main class="management-main" id="statistics-dashboard">
<section class="tb-hero tb-hero-compact"><span class="tb-eyebrow">PILOTAGE THIEBAPOWER</span><h2>Votre activité en un regard.</h2><p>Locations, dépassements, retours physiques et restitutions financières. Les informations affichées respectent vos droits d’accès.</p></section>
<section class="management-card stats-controls"><label>Période<select id="stats-days"><option value="1">Aujourd’hui</option><option value="7" selected>7 jours</option><option value="30">30 jours</option><option value="90">90 jours</option></select></label><label>Actualisation<select id="stats-interval"><option value="10">10 secondes</option><option value="15" selected>15 secondes</option><option value="30">30 secondes</option><option value="60">60 secondes</option></select></label><label class="stats-toggle"><input type="checkbox" id="stats-live"> Activer le temps réel</label><button class="admin-button" id="stats-refresh">Actualiser maintenant</button><p id="stats-status" role="status" aria-live="polite">Chargement des statistiques…</p><small>Horaires d’Abidjan (UTC). Données issues des événements enregistrés ; cache de 5 secondes maximum. Compteurs globaux instantanés, graphiques sur la période choisie.</small></section>
<div id="stats-cards" class="stats-cards"></div>
<div class="stats-grid" id="stats-charts"></div>
<div class="stats-grid" id="stats-lists"></div>
<p class="tb-muted">Un retour physique ne signifie pas que la caution a déjà été remboursée. Les incidents proviennent des rapports conservés, et ne représentent pas nécessairement un historique exhaustif.</p>
</main><?php require __DIR__.'/partials/admin_shell_end.php'; ?></body></html>
