<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Étiquettes des stations · Thiebapower</title><link rel="stylesheet" href="/style.css"></head><body class="admin-body label-page">
<?php $adminPageTitle='Étiquettes QR'; $adminPageOverline='PARC HEYCHARGE'; $adminPageSubtitle='Une étiquette par station, prête à imprimer'; require __DIR__.'/partials/admin_shell_start.php'; ?>
<div class="label-toolbar"><a href="/admin/stations">← Retour au parc</a><strong>A4 paysage · marges latérales 7 cm · marge haute 5 cm</strong><a class="admin-button" href="/admin/stations/labels.pdf<?= isset($_GET['imei'])?'?imei='.rawurlencode((string)$_GET['imei']):'' ?>">Télécharger le PDF A4</a><button type="button" onclick="window.print()">Imprimer</button></div>
<main class="label-sheet">
<?php foreach($labels as $station): ?><article class="station-label">
 <div class="label-top"><span class="label-brand">THIEBA<b>POWER</b></span><span class="label-tagline">Votre énergie, partout</span></div>
 <div class="label-hero"><div><p class="label-kicker">BATTERIES EXTERNES EN LIBRE SERVICE</p><h1>Louez une<br>batterie externe.</h1><p class="label-lead">Scannez le code avec votre téléphone. Choisissez votre batterie et payez en quelques instants.</p></div><div class="label-scan"><div class="label-qr"><?= $station['qr'] ?></div><strong>SCANNEZ POUR LOUER</strong><small><?= htmlspecialchars($station['label']?:'Station Thiebapower',ENT_QUOTES,'UTF-8') ?></small></div></div>
 <div class="label-footer"><div class="label-process" aria-label="Étapes de location"><div><span>▦</span><strong>Scannez</strong><small>le QR code</small></div><i>→</i><div><span>▣</span><strong>Choisissez</strong><small>un emplacement</small></div><i>→</i><div><span>▤</span><strong>Payez</strong><small>sur votre téléphone</small></div><i>→</i><div><span>ϟ</span><strong>Récupérez</strong><small>votre batterie</small></div></div><div class="label-payment"><span>Paiement mobile</span><b class="pay-wave">Wave</b><b class="pay-orange">Orange Money</b><b class="pay-mtn">MTN MoMo</b><b class="pay-moov">Moov Money</b></div><small class="label-id">Station <?= htmlspecialchars($station['imei'],ENT_QUOTES,'UTF-8') ?> · <?= htmlspecialchars($station['url'],ENT_QUOTES,'UTF-8') ?><?php if(!$station['enabled']): ?> · À activer avant installation<?php endif; ?></small></div>
 </article><?php endforeach; ?>
<?php if(!$labels): ?><p>Aucune étiquette disponible. Vérifiez l’URL du site et les stations synchronisées.</p><?php endif; ?>
</main><?php require __DIR__.'/partials/admin_shell_end.php'; ?></body></html>
