<!doctype html>
<html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Terminal <?= htmlspecialchars($station['imei'],ENT_QUOTES,'UTF-8') ?> · Thiebapower</title><link rel="stylesheet" href="/style.css"></head>
<body class="admin-body">
<?php $adminPageTitle='Détail du terminal'; $adminPageOverline='PARC HEYCHARGE'; $adminPageSubtitle='Inventaire et commandes du terminal'; require __DIR__.'/partials/admin_shell_start.php'; ?>
<main class="management-main"><p class="admin-overline">TERMINAL HEYCHARGE</p><h1><?= htmlspecialchars($station['label']?:$station['imei'],ENT_QUOTES,'UTF-8') ?></h1>
<p>IMEI <?= htmlspecialchars($station['imei'],ENT_QUOTES,'UTF-8') ?> · ICCID <?= htmlspecialchars((string)($station['iccid']??'—'),ENT_QUOTES,'UTF-8') ?> · <?= $station['enabled']?'Activé':'Désactivé' ?> · Dernière lecture <?= htmlspecialchars((string)($station['last_seen_at']??'Jamais'),ENT_QUOTES,'UTF-8') ?></p>
<section class="management-card"><h2>Contrôle du terminal</h2><div class="management-grid"><?php if(App\Services\Auth::can('fleet.manage')): ?><form method="post" action="/admin/stations/sync"><input type="hidden" name="csrf" value="<?= htmlspecialchars($_SESSION['csrf'],ENT_QUOTES,'UTF-8') ?>"><input type="hidden" name="imei" value="<?= htmlspecialchars($station['imei'],ENT_QUOTES,'UTF-8') ?>"><button class="admin-button">Synchroniser l’inventaire</button></form><?php endif; ?>
<?php if(App\Services\Auth::can('fleet.manage')): ?><form method="post" action="/admin/stations/toggle"><input type="hidden" name="csrf" value="<?= htmlspecialchars($_SESSION['csrf'],ENT_QUOTES,'UTF-8') ?>"><input type="hidden" name="imei" value="<?= htmlspecialchars($station['imei'],ENT_QUOTES,'UTF-8') ?>"><input type="hidden" name="enabled" value="<?= $station['enabled']?0:1 ?>"><button class="admin-ghost"><?= $station['enabled']?'Désactiver':'Activer' ?> les locations</button></form><?php endif; ?></div></section>
<section class="management-card"><h2>Batteries (<?= count($batteries) ?>)</h2><p>Une éjection manuelle retire la batterie des locations. La sortie est confirmée après une nouvelle lecture du terminal ; une issue inconnue ne doit pas être relancée sans vérification physique.</p><div class="management-table-wrap"><table><thead><tr><th>Emplacement</th><th>Numéro</th><th>Charge</th><th>État</th><th>Matériel</th><th>Caution propre</th><th>Action</th></tr></thead><tbody>
<?php foreach($batteries as $b): ?><tr><td><?= htmlspecialchars((string)($b['slot_id']??'—'),ENT_QUOTES,'UTF-8') ?></td><td><?= htmlspecialchars($b['serial'],ENT_QUOTES,'UTF-8') ?></td><td><?= $b['battery_capacity']===null?'—':(int)$b['battery_capacity'].' %' ?></td><td><?= htmlspecialchars($b['status'],ENT_QUOTES,'UTF-8') ?></td><td><?= $b['battery_abnormal']?'Batterie à contrôler':'Batterie OK' ?> · <?= $b['cable_abnormal']?'Câble à contrôler':'Câble OK' ?></td><td><?= $b['deposit_override']===null?'Tarif général':number_format((int)$b['deposit_override'],0,',',' ').' FCFA' ?></td><td>
<?php if(isset($openReleases[$b['id']])): ?>Éjection <?= $openReleases[$b['id']]['status']==='unknown'?'à vérifier':'en cours' ?>
<?php if(App\Services\Auth::can('fleet.manage')): ?><form method="post" action="/admin/stations/confirm-reinsertion"><input type="hidden" name="csrf" value="<?= htmlspecialchars($_SESSION['csrf'],ENT_QUOTES,'UTF-8') ?>"><input type="hidden" name="imei" value="<?= htmlspecialchars($station['imei'],ENT_QUOTES,'UTF-8') ?>"><input type="hidden" name="battery_id" value="<?= (int)$b['id'] ?>"><label>Numéro de la batterie réinsérée<input name="confirm_serial" required autocomplete="off" placeholder="<?= htmlspecialchars($b['serial'],ENT_QUOTES,'UTF-8') ?>"></label><button class="admin-ghost">Vérifier la réinsertion</button></form><?php endif; ?>
<?php elseif(in_array($b['status'],['available','maintenance','charging'],true) && $b['slot_id'] && App\Services\IntegrationSettings::all()['heycharge']==='normal'): ?>
<?php if(App\Services\Auth::can('fleet.release')): ?><form method="post" action="/admin/stations/release-battery" onsubmit="return confirm('Éjecter physiquement cette batterie du terminal ?');"><input type="hidden" name="csrf" value="<?= htmlspecialchars($_SESSION['csrf'],ENT_QUOTES,'UTF-8') ?>"><input type="hidden" name="imei" value="<?= htmlspecialchars($station['imei'],ENT_QUOTES,'UTF-8') ?>"><input type="hidden" name="battery_id" value="<?= (int)$b['id'] ?>"><label>Confirmer le numéro<input name="confirm_serial" required autocomplete="off" placeholder="<?= htmlspecialchars($b['serial'],ENT_QUOTES,'UTF-8') ?>"></label><button class="admin-ghost">Éjecter</button></form><?php endif; ?>
<?php else: ?>—<?php endif; ?></td></tr><?php endforeach; ?>
</tbody></table></div><?php if(!$batteries): ?><p>Aucune batterie reçue. Synchronisez le terminal.</p><?php endif; ?></section>
<section class="management-card"><h2>Éjections administrateur</h2><div class="management-table-wrap"><table><thead><tr><th>Batterie</th><th>Emplacement</th><th>État</th><th>Commande UTC</th><th>Clôture UTC</th></tr></thead><tbody><?php foreach($manualReleases as $command): ?><tr><td><?= htmlspecialchars($command['battery_serial'],ENT_QUOTES,'UTF-8') ?></td><td><?= htmlspecialchars($command['slot_id'],ENT_QUOTES,'UTF-8') ?></td><td><?= htmlspecialchars($command['status'],ENT_QUOTES,'UTF-8') ?></td><td><?= htmlspecialchars($command['requested_at'],ENT_QUOTES,'UTF-8') ?></td><td><?= htmlspecialchars((string)($command['confirmed_at']??'—'),ENT_QUOTES,'UTF-8') ?></td></tr><?php endforeach; ?></tbody></table></div></section>
<section class="management-card"><h2>Événements récents</h2><div class="management-table-wrap"><table><thead><tr><th>Date UTC</th><th>Type</th><th>Batterie</th></tr></thead><tbody><?php foreach($events as $event): ?><tr><td><?= htmlspecialchars($event['received_at'],ENT_QUOTES,'UTF-8') ?></td><td><?= htmlspecialchars($event['event_type'],ENT_QUOTES,'UTF-8') ?></td><td><?= htmlspecialchars((string)($event['battery_serial']??'—'),ENT_QUOTES,'UTF-8') ?></td></tr><?php endforeach; ?></tbody></table></div></section>
<section class="management-card"><h2>Locations récentes</h2><div class="management-table-wrap"><table><thead><tr><th>Référence</th><th>État</th><th>Création</th><th>Sortie</th><th>Retour</th></tr></thead><tbody><?php foreach($rentals as $r): ?><tr><td><?= htmlspecialchars($r['reference'],ENT_QUOTES,'UTF-8') ?></td><td><?= htmlspecialchars($r['status'],ENT_QUOTES,'UTF-8') ?></td><td><?= htmlspecialchars($r['created_at'],ENT_QUOTES,'UTF-8') ?></td><td><?= htmlspecialchars((string)($r['started_at']??'—'),ENT_QUOTES,'UTF-8') ?></td><td><?= htmlspecialchars((string)($r['returned_at']??'—'),ENT_QUOTES,'UTF-8') ?></td></tr><?php endforeach; ?></tbody></table></div></section>
</main><?php require __DIR__.'/partials/admin_shell_end.php'; ?></body></html>
