<!doctype html>
<html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Terminal <?= htmlspecialchars($station['imei'],ENT_QUOTES,'UTF-8') ?> · Thiebapower</title><link rel="stylesheet" href="/style.css"></head>
<body class="management-page"><header class="management-header"><a class="kiosk-logo" href="/admin">THIEBA<span>POWER</span></a><nav><a href="/admin/stations">Tous les terminaux</a><a href="/admin">Tableau de bord</a></nav></header>
<main class="management-main"><p class="admin-overline">TERMINAL HEYCHARGE</p><h1><?= htmlspecialchars($station['label']?:$station['imei'],ENT_QUOTES,'UTF-8') ?></h1>
<p>IMEI <?= htmlspecialchars($station['imei'],ENT_QUOTES,'UTF-8') ?> · ICCID <?= htmlspecialchars((string)($station['iccid']??'—'),ENT_QUOTES,'UTF-8') ?> · <?= $station['enabled']?'Activé':'Désactivé' ?> · Dernière lecture <?= htmlspecialchars((string)($station['last_seen_at']??'Jamais'),ENT_QUOTES,'UTF-8') ?></p>
<section class="management-card"><h2>Contrôle du terminal</h2><div class="management-grid"><form method="post" action="/admin/stations/sync"><input type="hidden" name="csrf" value="<?= htmlspecialchars($_SESSION['csrf'],ENT_QUOTES,'UTF-8') ?>"><input type="hidden" name="imei" value="<?= htmlspecialchars($station['imei'],ENT_QUOTES,'UTF-8') ?>"><button class="admin-button">Synchroniser l’inventaire</button></form>
<form method="post" action="/admin/stations/toggle"><input type="hidden" name="csrf" value="<?= htmlspecialchars($_SESSION['csrf'],ENT_QUOTES,'UTF-8') ?>"><input type="hidden" name="imei" value="<?= htmlspecialchars($station['imei'],ENT_QUOTES,'UTF-8') ?>"><input type="hidden" name="enabled" value="<?= $station['enabled']?0:1 ?>"><button class="admin-ghost"><?= $station['enabled']?'Désactiver':'Activer' ?> les locations</button></form></div></section>
<section class="management-card"><h2>Batteries (<?= count($batteries) ?>)</h2><div class="management-table-wrap"><table><thead><tr><th>Emplacement</th><th>Numéro</th><th>Charge</th><th>État</th><th>Matériel</th><th>Caution propre</th></tr></thead><tbody>
<?php foreach($batteries as $b): ?><tr><td><?= htmlspecialchars((string)($b['slot_id']??'—'),ENT_QUOTES,'UTF-8') ?></td><td><?= htmlspecialchars($b['serial'],ENT_QUOTES,'UTF-8') ?></td><td><?= $b['battery_capacity']===null?'—':(int)$b['battery_capacity'].' %' ?></td><td><?= htmlspecialchars($b['status'],ENT_QUOTES,'UTF-8') ?></td><td><?= $b['battery_abnormal']?'Batterie à contrôler':'Batterie OK' ?> · <?= $b['cable_abnormal']?'Câble à contrôler':'Câble OK' ?></td><td><?= $b['deposit_override']===null?'Tarif général':number_format((int)$b['deposit_override'],0,',',' ').' FCFA' ?></td></tr><?php endforeach; ?>
</tbody></table></div><?php if(!$batteries): ?><p>Aucune batterie reçue. Synchronisez le terminal.</p><?php endif; ?></section>
<section class="management-card"><h2>Événements récents</h2><div class="management-table-wrap"><table><thead><tr><th>Date UTC</th><th>Type</th><th>Batterie</th></tr></thead><tbody><?php foreach($events as $event): ?><tr><td><?= htmlspecialchars($event['received_at'],ENT_QUOTES,'UTF-8') ?></td><td><?= htmlspecialchars($event['event_type'],ENT_QUOTES,'UTF-8') ?></td><td><?= htmlspecialchars((string)($event['battery_serial']??'—'),ENT_QUOTES,'UTF-8') ?></td></tr><?php endforeach; ?></tbody></table></div></section>
<section class="management-card"><h2>Locations récentes</h2><div class="management-table-wrap"><table><thead><tr><th>Référence</th><th>État</th><th>Création</th><th>Sortie</th><th>Retour</th></tr></thead><tbody><?php foreach($rentals as $r): ?><tr><td><?= htmlspecialchars($r['reference'],ENT_QUOTES,'UTF-8') ?></td><td><?= htmlspecialchars($r['status'],ENT_QUOTES,'UTF-8') ?></td><td><?= htmlspecialchars($r['created_at'],ENT_QUOTES,'UTF-8') ?></td><td><?= htmlspecialchars((string)($r['started_at']??'—'),ENT_QUOTES,'UTF-8') ?></td><td><?= htmlspecialchars((string)($r['returned_at']??'—'),ENT_QUOTES,'UTF-8') ?></td></tr><?php endforeach; ?></tbody></table></div></section>
</main></body></html>
