<!doctype html>
<html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Parc de terminaux · Thiebapower</title><link rel="stylesheet" href="/style.css"></head>
<body class="admin-body">
<?php $adminPageTitle='Terminaux'; $adminPageOverline='PARC HEYCHARGE'; $adminPageSubtitle='Stations, inventaire et étiquettes QR'; require __DIR__.'/partials/admin_shell_start.php'; ?>
<main class="management-main">
<p class="admin-overline">PARC HEYCHARGE</p><h1>Terminaux et batteries</h1>
<p>Ajoutez une station par son IMEI, synchronisez son inventaire, puis activez-la pour la location. Les notifications HeyCharge enregistrent aussi les nouvelles stations.</p>
<section class="management-card"><h2>Compte HeyCharge et étiquettes</h2><?php if(App\Services\Auth::can('fleet.manage')): ?><form method="post" action="/admin/stations/discover"><input type="hidden" name="csrf" value="<?= htmlspecialchars($_SESSION['csrf'],ENT_QUOTES,'UTF-8') ?>"><label>IMEI de la nouvelle station<input name="imei" required maxlength="120" pattern="[A-Za-z0-9_-]+" placeholder="IMEI fourni par HeyCharge"></label><button class="admin-ghost">Importer cette station</button></form><?php endif; ?><p>HeyCharge ne fournit pas de liste globale dans cette API. L’import vérifie l’IMEI auprès de HeyCharge et récupère ses batteries ; une nouvelle station reste désactivée jusqu’à votre validation.</p><p><a class="admin-site-link" href="/admin/stations/labels">Prévisualiser les étiquettes</a> · <a class="admin-site-link" href="/admin/stations/labels.pdf">Télécharger le PDF A4</a></p></section>
<section class="management-card"><h2>État du parc</h2><p><?= count($stations) ?> terminaux · <?php foreach ($totals as $row): ?><?= htmlspecialchars($row['status'],ENT_QUOTES,'UTF-8') ?> : <?= (int)$row['quantity'] ?> · <?php endforeach; ?></p></section>
<section class="management-card"><h2>Terminaux</h2><div class="management-table-wrap"><table><thead><tr><th>Station</th><th>Connexion</th><th>Batteries</th><th>Disponibles</th><th>Charge min.</th><th>Dernière synchronisation</th><th>Actions</th></tr></thead><tbody>
<?php foreach($stations as $station): ?>
<?php $fresh=$station['last_seen_at'] && strtotime($station['last_seen_at'].' UTC') >= time()-600; ?>
<tr><td><a href="/admin/stations/detail?imei=<?= rawurlencode($station['imei']) ?>"><strong><?= htmlspecialchars($station['label']?:$station['imei'],ENT_QUOTES,'UTF-8') ?></strong></a><br><small><?= htmlspecialchars($station['imei'],ENT_QUOTES,'UTF-8') ?></small></td>
<td><?= $station['enabled'] ? 'Activé' : 'Désactivé' ?> · <?= $fresh ? 'Joignable récemment' : 'À vérifier' ?></td><td><?= (int)$station['batteries_count'] ?></td><td><?= (int)$station['available_count'] ?></td><td><?= $station['minimum_capacity']===null?'—':(int)$station['minimum_capacity'].' %' ?></td><td><?= htmlspecialchars((string)($station['last_seen_at']??'Jamais'),ENT_QUOTES,'UTF-8') ?></td>
<td><?php if(App\Services\Auth::can('fleet.manage')): ?><form method="post" action="/admin/stations/sync"><input type="hidden" name="csrf" value="<?= htmlspecialchars($_SESSION['csrf'],ENT_QUOTES,'UTF-8') ?>"><input type="hidden" name="imei" value="<?= htmlspecialchars($station['imei'],ENT_QUOTES,'UTF-8') ?>"><button class="admin-ghost">Synchroniser</button></form><?php endif; ?><a href="/admin/stations/detail?imei=<?= rawurlencode($station['imei']) ?>">Détails</a> · <a href="/admin/stations/labels?imei=<?= rawurlencode($station['imei']) ?>">Étiquette</a></td></tr>
<?php endforeach; ?>
</tbody></table></div><?php if(!$stations): ?><p>Aucun terminal enregistré. Importez les stations associées à la clé API.</p><?php endif; ?></section>
</main><?php require __DIR__.'/partials/admin_shell_end.php'; ?></body></html>
