<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Lieu et gérant · Thiebapower</title><link rel="stylesheet" href="/style.css"><link rel="stylesheet" href="/vendor/leaflet/leaflet.css"><link rel="stylesheet" href="/station-experience.css?v=1"><script src="/vendor/leaflet/leaflet.js" defer></script><script src="/station-profile.js?v=1" defer></script></head><body class="admin-body">
<?php $adminPageTitle='Lieu et gérant';$adminPageSubtitle=$station['label']?:$station['imei'];require __DIR__.'/partials/admin_shell_start.php';$h=static fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');$editable=App\Services\Auth::can('fleet.manage'); ?>
<main class="management-main"><p><a href="/admin/stations/detail?imei=<?= rawurlencode($station['imei']) ?>">Retour au terminal</a></p>
<?php if(isset($_GET['saved'])): ?><p class="station-feedback" role="status">Les informations de la station ont été enregistrées.</p><?php endif; ?>
<form method="post" action="/admin/stations/profile" id="station-profile" data-editable="<?= $editable?'1':'0' ?>">
<input type="hidden" name="csrf" value="<?= $h($_SESSION['csrf']) ?>"><input type="hidden" name="imei" value="<?= $h($station['imei']) ?>">
<section class="management-card"><h2>Identité et emplacement</h2><p>Donnez un nom reconnaissable au lieu. Recherchez un quartier, une adresse ou un établissement, choisissez une suggestion puis ajustez le marqueur sur la carte.</p>
<fieldset <?= $editable?'':'disabled' ?>><div class="management-grid"><label>Nom de la station<input name="label" required maxlength="160" value="<?= $h($station['label']) ?>" placeholder="Thieba Power · Café de Koumassi"></label><label>Type de lieu<input name="venue_type" maxlength="80" value="<?= $h($station['venue_type']??'') ?>" placeholder="Restaurant, hôtel, bar…"></label><label>Horaires d’accès<input name="opening_hours" maxlength="250" value="<?= $h($station['opening_hours']??'') ?>" placeholder="Lun–sam : 8h–22h"></label></div>
<label>Adresse et indications d’accès<input name="address" id="station-address" maxlength="500" value="<?= $h($station['address']??'') ?>" placeholder="Quartier, rue, repère et entrée"></label>
<label>Rechercher un lieu<input id="place-query" type="search" maxlength="160" autocomplete="off" placeholder="Exemple : Cap Sud, Abidjan" aria-controls="place-results"></label><div id="place-results" class="place-results"></div></fieldset>
<p id="place-status" role="status">La carte permet aussi de placer le marqueur par un clic.</p><div id="station-editor-map" class="station-map" aria-label="Emplacement de la station"></div>
<input type="hidden" name="latitude" id="station-latitude" value="<?= $h($station['latitude']??'') ?>"><input type="hidden" name="longitude" id="station-longitude" value="<?= $h($station['longitude']??'') ?>">
<?php if($editable): ?><p><button type="button" class="admin-ghost" id="use-location">Utiliser ma position actuelle</button> <button type="button" class="admin-ghost" id="clear-location">Retirer le positionnement</button></p><?php endif; ?></section>
<section class="management-card"><h2>Gérant du lieu</h2><p>Ces informations sont réservées à l’administration.</p><fieldset <?= $editable?'':'disabled' ?>><div class="management-grid"><label>Nom et prénom<input name="manager_name" maxlength="160" value="<?= $h($station['manager_name']??'') ?>"></label><label>Téléphone<input name="manager_phone" type="tel" maxlength="30" value="<?= $h($station['manager_phone']??'') ?>"></label><label>Email<input name="manager_email" type="email" maxlength="190" value="<?= $h($station['manager_email']??'') ?>"></label></div><label>Notes internes<textarea name="manager_notes" maxlength="2000" rows="3"><?= $h($station['manager_notes']??'') ?></textarea></label></fieldset></section>
<?php if($editable): ?><button class="admin-button">Enregistrer la fiche de station</button><?php endif; ?></form></main><?php require __DIR__.'/partials/admin_shell_end.php'; ?></body></html>
