<!doctype html>
<html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Trouver une station · Thiebapower</title><link rel="stylesheet" href="/style.css"><link rel="stylesheet" href="/station-experience.css?v=20261004-2"><link rel="stylesheet" href="/vendor/leaflet/leaflet.css"><script src="/vendor/leaflet/leaflet.js" defer></script><script src="/station-directory.js?v=20261004-2" defer></script></head>
<body class="kiosk station-finder-page">
<header class="kiosk-header"><a class="kiosk-logo" href="/">THIEBA<span>POWER</span></a><a class="finder-account" href="/my-rentals">Mes locations <span aria-hidden="true">↗</span></a></header>
<main class="station-directory station-finder">
<section class="finder-intro"><span class="finder-eyebrow">LE RÉSEAU THIEBA POWER</span><h1>Votre prochaine recharge<br><span>est juste à côté.</span></h1><p>Trouvez une station, consultez les batteries disponibles et préparez votre trajet.</p></section>
<section class="finder-search-section" aria-label="Rechercher une station">
<div class="finder-search-bar"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"></circle><path d="m16 16 4.5 4.5"></path></svg><label class="finder-sr-only" for="station-filter">Filtrer les stations par nom, quartier ou adresse</label><input id="station-filter" type="search" autocomplete="off" placeholder="Rechercher une station, un quartier, une adresse…" aria-controls="station-directory-list"><button id="clear-station-filter" type="button" aria-label="Effacer la recherche" hidden>×</button></div>
<div class="finder-search-tools"><button type="button" id="near-me" class="finder-location-button"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="7"></circle><circle cx="12" cy="12" r="2"></circle><path d="M12 2v3m0 14v3M2 12h3m14 0h3"></path></svg>Autour de moi</button><button type="button" id="refresh-stations" class="finder-refresh-button">Actualiser</button><p id="directory-status" role="status" aria-live="polite">Chargement des stations…</p></div>
</section>
<div class="finder-layout"><section class="finder-map-panel" aria-label="Carte du réseau"><div class="station-map" id="station-directory-map" aria-label="Carte des stations"></div><div class="finder-legend"><span><i class="legend-dot is-active"></i>Activée et joignable</span><span><i class="legend-dot is-uncertain"></i>Connexion à vérifier</span><span><i class="legend-dot is-inactive"></i>Locations suspendues</span></div></section><section class="finder-results-panel" aria-label="Stations trouvées"><div class="finder-results-heading"><h2>Les stations</h2><span id="station-result-count">—</span></div><div class="station-directory-list" id="station-directory-list"></div></section></div>
<p class="finder-footnote">Les disponibilités proviennent de la dernière lecture des terminaux. Les horaires sont ceux du lieu d’accueil ; vérifiez-les avant de vous déplacer.</p>
</main><?php require __DIR__.'/partials/public_support.php'; ?></body></html>
