<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Système · Thiebapower</title><link rel="stylesheet" href="/style.css"></head><body class="admin-body">
<?php $adminPageTitle='Administration système';$adminPageSubtitle='Réglages du suivi et rapports d’incident.';require __DIR__.'/partials/admin_shell_start.php';$esc=static fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8'); ?>
<main class="management-main">
<?php if(isset($storageReady)&&!$storageReady): ?><p class="admin-card" role="alert">Stockage système non inscriptible : les nouveaux rapports restent uniquement dans le journal PHP. Corrigez les droits du dossier privé.</p><?php endif; ?>
<?php if(isset($_GET['saved'])): ?><p class="admin-card" role="status">Réglage enregistré. Les pages ouvertes l’appliqueront à leur prochaine vérification.</p><?php endif; ?>
<section class="admin-card"><span class="tb-eyebrow">SUIVI DU DASHBOARD</span><h2>Compteurs d’utilisation</h2><p>La désactivation s’applique à tous les administrateurs. Elle supprime les lectures SQL liées aux compteurs et le calcul chaque seconde. Les alertes restent actives.</p><form method="post" action="/admin/system/settings"><input type="hidden" name="csrf" value="<?= $esc($adminCsrf) ?>"><label><input type="checkbox" name="counters_enabled" value="1" <?= $enabled?'checked':'' ?>> Activer les compteurs</label><button type="submit" class="btn">Enregistrer</button></form></section>
<section class="admin-card"><span class="tb-eyebrow">DIAGNOSTIC</span><h2>Rapports d’incident</h2><p>Signalés dans la cloche. 200 rapports récents maximum ; les secrets et coordonnées sont masqués. « Pris en compte » clôture le signalement pour tous les administrateurs, sans modifier la location.</p><form method="get" action="/admin/system" class="tb-toolbar"><label>Rechercher un diagnostic, une référence ou une étape<input type="search" name="search" value="<?= $esc($filter) ?>" placeholder="Référence de diagnostic…"></label><button class="btn" type="submit">Rechercher</button></form>
<?php if(!$reports): ?><p class="tb-empty">Aucun rapport correspondant.</p><?php endif; ?>
<div class="tb-battery-grid"><?php foreach($reports as $report): ?><article class="tb-battery-card" id="report-<?= $esc($report['id']) ?>"><span class="tb-eyebrow"><?= $esc($report['stage']) ?></span><h3><?= $report['acknowledged']?'Pris en compte':'À examiner' ?></h3><p><?= $esc($report['created_at']) ?></p><p>Diagnostic : <code><?= $esc($report['diagnostic']) ?></code></p><?php if($report['reference']): ?><a href="/admin/rentals/detail?reference=<?= rawurlencode($report['reference']) ?>"><?= $esc($report['reference']) ?></a><?php endif; ?><p><?= $esc($report['exception']) ?> · <?= $esc($report['message']) ?></p><?php if($report['steps']): ?><details><summary>Durées des étapes</summary><ul><?php foreach($report['steps'] as $step): ?><li><?= $esc($step['stage']) ?> : <?= (int)$step['duration_ms'] ?> ms · <?= $esc($step['outcome']) ?></li><?php endforeach; ?></ul></details><?php endif; ?><?php if(!$report['acknowledged']): ?><form method="post" action="/admin/system/acknowledge"><input type="hidden" name="csrf" value="<?= $esc($adminCsrf) ?>"><input type="hidden" name="id" value="<?= $esc($report['id']) ?>"><button class="admin-ghost" type="submit">Pris en compte</button></form><?php endif; ?></article><?php endforeach; ?></div></section>
<section class="admin-card"><h2>Stockage et protection de la plateforme</h2><p>Les rapports ne nécessitent aucune écriture SQL. Si le stockage est indisponible, le rapport est envoyé au journal PHP avec le préfixe <code>TBP_INCIDENT</code>. La collecte ne relance jamais un paiement. Les erreurs fatales sont collectées dans la mesure où PHP peut encore exécuter sa routine de fermeture.</p><p>Les alertes sont visibles sur cette interface et dans la cloche ; aucun email ou SMS n’est encore envoyé.</p></section>
</main><?php require __DIR__.'/partials/admin_shell_end.php'; ?></body></html>
