CREATE TABLE pricing (id TINYINT PRIMARY KEY, rental_fee INT UNSIGNED NOT NULL, default_deposit INT UNSIGNED NOT NULL, duration_minutes INT UNSIGNED NOT NULL, late_percent TINYINT UNSIGNED NOT NULL);
INSERT INTO pricing VALUES (1,1000,5000,60,10);
CREATE TABLE batteries (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, serial VARCHAR(100) NOT NULL UNIQUE, deposit_override INT UNSIGNED NULL, status ENUM('available','reserved','rented','maintenance') NOT NULL DEFAULT 'available');
CREATE TABLE rentals (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, reference VARCHAR(50) NOT NULL UNIQUE, battery_id BIGINT UNSIGNED NOT NULL, customer_name VARCHAR(160) NOT NULL, customer_email VARCHAR(190) NOT NULL, customer_phone VARCHAR(30) NOT NULL, rental_fee INT UNSIGNED NOT NULL, deposit INT UNSIGNED NOT NULL, late_percent TINYINT UNSIGNED NOT NULL, duration_minutes INT UNSIGNED NOT NULL, status ENUM('pending_payment','paid','releasing','active','returned','payment_failed','release_failed') NOT NULL, started_at DATETIME NULL, due_at DATETIME NULL, returned_at DATETIME NULL, late_charge INT UNSIGNED NOT NULL DEFAULT 0, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (battery_id) REFERENCES batteries(id));
CREATE TABLE payment_notifications (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, rental_id BIGINT UNSIGNED NOT NULL, payload JSON NOT NULL, received_at DATETIME NOT NULL, FOREIGN KEY (rental_id) REFERENCES rentals(id));
CREATE TABLE deposit_settlements (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, rental_id BIGINT UNSIGNED NOT NULL UNIQUE, deduction INT UNSIGNED NOT NULL, refund_amount INT UNSIGNED NOT NULL, status ENUM('pending','processing','refunded','failed') NOT NULL DEFAULT 'pending', provider_reference VARCHAR(120) NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (rental_id) REFERENCES rentals(id));
CREATE TABLE integration_settings (name VARCHAR(32) NOT NULL PRIMARY KEY, mode VARCHAR(32) NOT NULL, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
INSERT INTO integration_settings(name,mode) VALUES ('paiementpro','sandbox'),('heycharge','simulation');
-- For fresh installations, apply database/migrations/20260928_automatic_deposit_refunds.sql after this schema.
