CREATE TABLE IF NOT EXISTS station_label_settings (
 id TINYINT UNSIGNED PRIMARY KEY,
 margin_left DECIMAL(6,2) NOT NULL DEFAULT 50,
 margin_right DECIMAL(6,2) NOT NULL DEFAULT 50,
 margin_top DECIMAL(6,2) NOT NULL DEFAULT 70,
 margin_bottom DECIMAL(6,2) NOT NULL DEFAULT 70,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
INSERT IGNORE INTO station_label_settings(id) VALUES (1);
