CREATE TABLE IF NOT EXISTS public_experience_settings (
 id TINYINT UNSIGNED PRIMARY KEY,
 configuration TEXT NOT NULL,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
