CREATE TABLE IF NOT EXISTS sms_templates (
 template_key VARCHAR(40) NOT NULL PRIMARY KEY,
 content TEXT NOT NULL,
 enabled TINYINT NOT NULL DEFAULT 0,
 enabled_at DATETIME NULL,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS sms_outbox (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 template_key VARCHAR(40) NOT NULL,
 rental_id BIGINT UNSIGNED NOT NULL,
 event_key CHAR(64) NOT NULL UNIQUE,
 state VARCHAR(24) NOT NULL DEFAULT 'queued',
 http_status SMALLINT UNSIGNED NULL,
 resource_id VARCHAR(190) NULL,
 created_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
 claimed_at DATETIME NULL,
 INDEX(state,id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS phone_otp_challenges (
 challenge_id CHAR(32) NOT NULL PRIMARY KEY,
 phone VARCHAR(30) NOT NULL,
 purpose VARCHAR(40) NOT NULL,
 code_hash CHAR(64) NOT NULL,
 attempts TINYINT UNSIGNED NOT NULL DEFAULT 0,
 expires_at DATETIME NOT NULL,
 used_at DATETIME NULL,
 created_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
 INDEX(phone,purpose,created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
