CREATE TABLE IF NOT EXISTS orange_sms_settings (
 id TINYINT UNSIGNED NOT NULL PRIMARY KEY,
 configuration LONGTEXT NOT NULL,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT IGNORE INTO orange_sms_settings(id,configuration) VALUES(1,'{}');
CREATE TABLE IF NOT EXISTS orange_sms_logs (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
 user_id BIGINT UNSIGNED NULL,
 operation VARCHAR(24) NOT NULL,
 mode VARCHAR(16) NOT NULL,
 recipient_masked VARCHAR(32) NULL,
 state VARCHAR(24) NOT NULL DEFAULT 'processing',
 http_status SMALLINT UNSIGNED NULL,
 resource_id VARCHAR(190) NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 INDEX(created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
